const words = [
    { korean: "자전거", english: "bicycle", pronunciation: "[ˈbaɪsɪkəl]" },
    { korean: "큰", english: "big", pronunciation: "[bɪɡ]" },
    { korean: "새", english: "bird", pronunciation: "[bɜrd]" },
    { korean: "생일", english: "birthday", pronunciation: "[ˈbɜrθˌdeɪ]" },
    { korean: "검정색", english: "black", pronunciation: "[blæk]" },
    { korean: "불다", english: "blow", pronunciation: "[bloʊ]" },
    { korean: "푸른", english: "blue", pronunciation: "[blu]" },
    { korean: "판자", english: "board", pronunciation: "[bɔrd]" },
    { korean: "배", english: "boat", pronunciation: "[boʊt]" },
    { korean: "몸", english: "body", pronunciation: "[ˈbɑdi]" },
    { korean: "책", english: "book", pronunciation: "[bʊk]" },
    { korean: "병", english: "bottle", pronunciation: "[ˈbɑtəl]" },
    { korean: "사발", english: "bowl", pronunciation: "[boʊl]" },
    { korean: "상자", english: "box", pronunciation: "[bɑks]" },
    { korean: "소년", english: "boy", pronunciation: "[bɔɪ]" },
    { korean: "빵", english: "bread", pronunciation: "[brɛd]" },
    { korean: "깨뜨리다", english: "break", pronunciation: "[breɪk]" },
    { korean: "아침", english: "breakfast", pronunciation: "[ˈbrɛkfəst]" },
    { korean: "다리", english: "bridge", pronunciation: "[brɪdʒ]" },
    { korean: "밝은", english: "bright", pronunciation: "[braɪt]" },
    { korean: "가져오다", english: "bring", pronunciation: "[brɪŋ]" },
    { korean: "형제", english: "brother", pronunciation: "[ˈbrʌðər]" },
    { korean: "갈색", english: "brown", pronunciation: "[braʊn]" },
    { korean: "솔", english: "brush", pronunciation: "[brʌʃ]" },
    { korean: "건설하다", english: "build", pronunciation: "[bɪld]" },
    { korean: "불타다", english: "burn", pronunciation: "[bɜrn]" },
    { korean: "버스", english: "bus", pronunciation: "[bʌs]" },
    { korean: "바쁜", english: "busy", pronunciation: "[ˈbɪzi]" },
    { korean: "그러나", english: "but", pronunciation: "[bʌt]" },
    { korean: "버터", english: "butter", pronunciation: "[ˈbʌtər]" },
    { korean: "단추", english: "button", pronunciation: "[ˈbʌtən]" },
    { korean: "사다", english: "buy", pronunciation: "[baɪ]" },
    { korean: "옆에", english: "by", pronunciation: "[baɪ]" },
    { korean: "안녕", english: "bye", pronunciation: "[baɪ]" },
    { korean: "달력", english: "calendar", pronunciation: "[ˈkæləndər]" },
    { korean: "케이크", english: "cake", pronunciation: "[keɪk]" },
    { korean: "부르다", english: "call", pronunciation: "[kɔl]" },
    { korean: "사진기", english: "camera", pronunciation: "[ˈkæmərə]" },
    { korean: "야영지", english: "camp", pronunciation: "[kæmp]" },
    { korean: "할 수 있다", english: "can", pronunciation: "[kæn]" },
    { korean: "양초", english: "candle", pronunciation: "[ˈkændəl]" },
    { korean: "사탕", english: "candy", pronunciation: "[ˈkændi]" },
    { korean: "모자", english: "cap", pronunciation: "[kæp]" },
    { korean: "수도, 대문자", english: "capital", pronunciation: "[ˈkæpɪtəl]" },
    { korean: "우두머리", english: "captain", pronunciation: "[ˈkæptən]" },
    { korean: "자동차", english: "car", pronunciation: "[kɑr]" },
    { korean: "카드", english: "card", pronunciation: "[kɑrd]" },
    { korean: "걱정, 돌보다", english: "care", pronunciation: "[kɛr]" },
    { korean: "나르다", english: "carry", pronunciation: "[ˈkæri]" },
    { korean: "경우", english: "case", pronunciation: "[keɪs]" },
    { korean: "카세트", english: "cassette", pronunciation: "[kəˈsɛt]" },
    { korean: "고양이", english: "cat", pronunciation: "[kæt]" },
    { korean: "붙잡다", english: "catch", pronunciation: "[kæʧ]" },
    { korean: "천장", english: "ceiling", pronunciation: "[ˈsilɪŋ]" },
    { korean: "중앙", english: "center", pronunciation: "[ˈsɛntər]" },
    { korean: "의자", english: "chair", pronunciation: "[ʧɛr]" },
    { korean: "분필", english: "chalk", pronunciation: "[ʧɔk]" },
    { korean: "기회", english: "chance", pronunciation: "[ʧæns]" },
    { korean: "바꾸다", english: "change", pronunciation: "[ʧeɪndʒ]" },
    { korean: "값싼", english: "cheap", pronunciation: "[ʧip]" },
    { korean: "치즈", english: "cheese", pronunciation: "[ʧiz]" },
    { korean: "닭", english: "chicken", pronunciation: "[ˈʧɪkɪn]" },
    { korean: "어린이", english: "child", pronunciation: "[ʧaɪld]" },
    { korean: "젓가락", english: "chopstick", pronunciation: "[ˈʧɑpˌstɪk]" },
    { korean: "교회", english: "church", pronunciation: "[ʧɜrʧ]" },
    { korean: "원", english: "circle", pronunciation: "[ˈsɜrkəl]" },
    { korean: "도시", english: "city", pronunciation: "[ˈsɪti]" },
    { korean: "학급", english: "class", pronunciation: "[klæs]" },
    { korean: "동급생", english: "classmate", pronunciation: "[ˈklæsˌmeɪt]" },
    { korean: "깨끗한", english: "clean", pronunciation: "[klin]" },
    { korean: "오르다", english: "climb", pronunciation: "[klaɪm]" },
    { korean: "시계", english: "clock", pronunciation: "[klɑk]" },
    { korean: "닫다", english: "close", pronunciation: "[kloʊz]" },
    { korean: "옷", english: "clothes", pronunciation: "[kloʊðz]" },
    { korean: "구름", english: "cloud", pronunciation: "[klaʊd]" },
    { korean: "클럽", english: "club", pronunciation: "[klʌb]" },
    { korean: "코트", english: "coat", pronunciation: "[koʊt]" },
    { korean: "커피", english: "coffee", pronunciation: "[ˈkɔfi]" },
    { korean: "동전", english: "coin", pronunciation: "[kɔɪn]" },
    { korean: "추운", english: "cold", pronunciation: "[koʊld]" },
    { korean: "색깔", english: "color", pronunciation: "[ˈkʌlər]" },
    { korean: "오다", english: "come", pronunciation: "[kʌm]" },
    { korean: "컴퓨터", english: "computer", pronunciation: "[kəmˈpjutər]" },
    { korean: "요리하다", english: "cook", pronunciation: "[kʊk]" },
    { korean: "시원한", english: "cool", pronunciation: "[kul]" },
    { korean: "사본, 베끼다", english: "copy", pronunciation: "[ˈkɑpi]" },
    { korean: "모퉁이", english: "corner", pronunciation: "[ˈkɔrnər]" },
    { korean: "세다", english: "count", pronunciation: "[kaʊnt]" },
    { korean: "지역", english: "country", pronunciation: "[ˈkʌntri]" },
    { korean: "과정", english: "course", pronunciation: "[kɔrs]" },
    { korean: "사촌", english: "cousin", pronunciation: "[ˈkʌzən]" },
    { korean: "덮다", english: "cover", pronunciation: "[ˈkʌvər]" },
    { korean: "암소", english: "cow", pronunciation: "[kaʊ]" },
    { korean: "크레용", english: "crayon", pronunciation: "[ˈkreɪˌɑn]" },
    { korean: "크림", english: "cream", pronunciation: "[krim]" },
    { korean: "가로지르다", english: "cross", pronunciation: "[krɔs]" },
    { korean: "울다", english: "cry", pronunciation: "[kraɪ]" },
    { korean: "컵", english: "cup", pronunciation: "[kʌp]" },
    { korean: "커튼", english: "curtain", pronunciation: "[ˈkɜrtən]" },
    { korean: "자르다", english: "cut", pronunciation: "[kʌt]" },
    { korean: "아빠", english: "dad(dy)", pronunciation: "[dæd(i)]" },
    { korean: "춤추다", english: "dance", pronunciation: "[dæns]" },
    { korean: "위험한", english: "danger", pronunciation: "[ˈdeɪndʒər]" },
    { korean: "어두운", english: "dark", pronunciation: "[dɑrk]" },
    { korean: "날짜", english: "date", pronunciation: "[deɪt]" },
    { korean: "딸", english: "daughter", pronunciation: "[ˈdɔtər]" },
    { korean: "낮, 하루", english: "day", pronunciation: "[deɪ]" },
    { korean: "죽은", english: "dead", pronunciation: "[dɛd]" },
    { korean: "깊은", english: "deep", pronunciation: "[dip]" },
    { korean: "존경하는", english: "dear", pronunciation: "[dɪr]" },
    { korean: "책상", english: "desk", pronunciation: "[dɛsk]" },
    { korean: "다이얼", english: "dial", pronunciation: "[ˈdaɪəl]" },
    { korean: "일기", english: "diary", pronunciation: "[ˈdaɪəri]" },
    { korean: "사전", english: "dictionary", pronunciation: "[ˈdɪkʃəˌnɛri]" },
    { korean: "죽다", english: "die", pronunciation: "[daɪ]" },
    { korean: "저녁", english: "dinner", pronunciation: "[ˈdɪnər]" },
    { korean: "더러운", english: "dirty", pronunciation: "[ˈdɜrti]" },
    { korean: "큰 접시", english: "dish", pronunciation: "[dɪʃ]" },
    { korean: "하다", english: "do", pronunciation: "[du]" },
    { korean: "의사", english: "doctor", pronunciation: "[ˈdɑktər]" },
    { korean: "개", english: "dog", pronunciation: "[dɔɡ]" },
    { korean: "인형", english: "doll", pronunciation: "[dɑl]" },
    { korean: "달러", english: "dollar", pronunciation: "[ˈdɑlər]" },
    { korean: "돌고래", english: "dolphin", pronunciation: "[ˈdɑlfɪn]" },
    { korean: "문", english: "door", pronunciation: "[dɔr]" },
    { korean: "아래에", english: "down", pronunciation: "[daʊn]" },
    { korean: "그리다", english: "draw", pronunciation: "[drɔ]" },
    { korean: "꿈", english: "dream", pronunciation: "[drim]" },
    { korean: "드레스", english: "dress", pronunciation: "[drɛs]" },
    { korean: "마시다", english: "drink", pronunciation: "[drɪŋk]" },
    { korean: "운전하다", english: "drive", pronunciation: "[draɪv]" },
    { korean: "떨어지다, 방울", english: "drop", pronunciation: "[drɑp]" },
    { korean: "북", english: "drum", pronunciation: "[drʌm]" },
    { korean: "마른", english: "dry", pronunciation: "[draɪ]" },
    { korean: "오리", english: "duck", pronunciation: "[dʌk]" },
    { korean: "귀", english: "ear", pronunciation: "[ɪr]" },
    { korean: "일찍", english: "early", pronunciation: "[ˈɜrli]" },
    { korean: "지구", english: "earth", pronunciation: "[ɜrθ]" },
    { korean: "동쪽", english: "east", pronunciation: "[ist]" },
    { korean: "쉬운", english: "easy", pronunciation: "[ˈizi]" },
    { korean: "먹다", english: "eat", pronunciation: "[it]" },
    { korean: "계란", english: "egg", pronunciation: "[ɛɡ]" },
    { korean: "텅 빈", english: "empty", pronunciation: "[ˈɛmpti]" },
    { korean: "끝", english: "end", pronunciation: "[ɛnd]" },
    { korean: "엔진", english: "engine", pronunciation: "[ˈɛndʒən]" },
    { korean: "즐기다", english: "enjoy", pronunciation: "[ɛnˈdʒɔɪ]" },
    { korean: "충분한", english: "enough", pronunciation: "[ɪˈnʌf]" },
    { korean: "지우개", english: "eraser", pronunciation: "[ɪˈreɪsər]" },
    { korean: "저녁", english: "evening", pronunciation: "[ˈivnɪŋ]" },
    { korean: "모든, 모두의", english: "every", pronunciation: "[ˈɛvəri]" },
    { korean: "예, 보기", english: "example", pronunciation: "[ɪɡˈzæmpəl]" },
    { korean: "뛰어난", english: "excellent", pronunciation: "[ˈɛksələnt]" },
    { korean: "흥분시키다", english: "excite", pronunciation: "[ɪkˈsaɪt]" },
    { korean: "용서하다", english: "excuse", pronunciation: "[ɪkˈskjuz]" },
    { korean: "연습", english: "exercise", pronunciation: "[ˈɛksərˌsaɪz]" },
    { korean: "눈", english: "eye", pronunciation: "[aɪ]" },
    { korean: "얼굴", english: "face", pronunciation: "[feɪs]" },
    { korean: "사실", english: "fact", pronunciation: "[fækt]" },
    { korean: "공정한", english: "fair", pronunciation: "[fɛr]" },
    { korean: "가을, 떨어지다", english: "fall", pronunciation: "[fɔl]" },
    { korean: "가족", english: "family", pronunciation: "[ˈfæməli]" },
    { korean: "멀리 떨어진", english: "far", pronunciation: "[fɑr]" },
    { korean: "농장", english: "farm", pronunciation: "[fɑrm]" },
    { korean: "빠른", english: "fast", pronunciation: "[fæst]" },
    { korean: "쌀찐", english: "fat", pronunciation: "[fæt]" },
    { korean: "유명한", english: "famous", pronunciation: "[ˈfeɪməs]" },
    { korean: "아버지", english: "father", pronunciation: "[ˈfɑðər]" },
    { korean: "느끼다", english: "feel", pronunciation: "[fil]" },
    { korean: "다소 양이 적은", english: "few", pronunciation: "[fju]" },
    { korean: "들판, 경기장", english: "field", pronunciation: "[fild]" },
    { korean: "싸움", english: "fight", pronunciation: "[faɪt]" },
    { korean: "채우다", english: "fill", pronunciation: "[fɪl]" },
    { korean: "필름", english: "film", pronunciation: "[fɪlm]" },
    { korean: "찾다", english: "find", pronunciation: "[faɪnd]" },
    { korean: "좋은, 맑은", english: "fine", pronunciation: "[faɪn]" },
    { korean: "손가락", english: "finger", pronunciation: "[ˈfɪŋɡər]" },
    { korean: "끝내다", english: "finish", pronunciation: "[ˈfɪnɪʃ]" },
    { korean: "불", english: "fire", pronunciation: "[ˈfaɪər]" },
    { korean: "고기, 낚시하다", english: "fish", pronunciation: "[fɪʃ]" },
    { korean: "고정시키다", english: "fix", pronunciation: "[fɪks]" },
    { korean: "깃발", english: "flag", pronunciation: "[flæɡ]" },
    { korean: "마루", english: "floor", pronunciation: "[flɔr]" },
    { korean: "꽃", english: "flower", pronunciation: "[ˈflaʊər]" },
    { korean: "날다", english: "fly", pronunciation: "[flaɪ]" },
    { korean: "뒤를 따르다", english: "follow", pronunciation: "[ˈfɑloʊ]" },
    { korean: "음식", english: "food", pronunciation: "[fud]" },
    { korean: "바보", english: "fool", pronunciation: "[ful]" },
    { korean: "발", english: "foot", pronunciation: "[fʊt]" },
    { korean: "위하여, 동안", english: "for", pronunciation: "[fɔr]" },
    { korean: "잊다", english: "forget", pronunciation: "[fərˈɡɛt]" },
    { korean: "포크", english: "fork", pronunciation: "[fɔrk]" },
    { korean: "자유로운", english: "free", pronunciation: "[fri]" },
    { korean: "신선한", english: "fresh", pronunciation: "[frɛʃ]" },
    { korean: "친구", english: "friend", pronunciation: "[frɛnd]" },
    { korean: "로부터", english: "from", pronunciation: "[frʌm]" },
    { korean: "앞, 정면", english: "front", pronunciation: "[frʌnt]" },
    { korean: "과일", english: "fruit", pronunciation: "[frut]" },
    { korean: "가득 찬", english: "full", pronunciation: "[fʊl]" },
    { korean: "즐거움", english: "fun", pronunciation: "[fʌn]" },
    { korean: "놀이", english: "game", pronunciation: "[ɡeɪm]" },
    { korean: "정원", english: "garden", pronunciation: "[ˈɡɑrdən]" },
    { korean: "가스, 휘발유", english: "gas", pronunciation: "[ɡæs]" },
    { korean: "문", english: "gate", pronunciation: "[ɡeɪt]" },
    { korean: "온화한", english: "gentle", pronunciation: "[ˈdʒɛntəl]" },
    { korean: "얻다", english: "get", pronunciation: "[ɡɛt]" },
    { korean: "소녀", english: "girl", pronunciation: "[ɡɜrl]" },
    { korean: "주다", english: "give", pronunciation: "[ɡɪv]" },
    { korean: "기쁜", english: "glad", pronunciation: "[ɡlæd]" },
    { korean: "유리, 컵", english: "glass", pronunciation: "[ɡlæs]" },
    { korean: "장갑", english: "glove", pronunciation: "[ɡlʌv]" },
    { korean: "가다", english: "go", pronunciation: "[ɡoʊ]" },
    { korean: "신, 하나님", english: "god(GOD)", pronunciation: "[ɡɑd]" },
    { korean: "금", english: "gold", pronunciation: "[ɡoʊld]" },
    { korean: "좋은", english: "good", pronunciation: "[ɡʊd]" },
    { korean: "할머니", english: "grandmother", pronunciation: "[ˈɡrænmʌðər]" },
    { korean: "포도", english: "grape", pronunciation: "[ɡreɪp]" },
    { korean: "풀, 잔디", english: "grass", pronunciation: "[ɡræs]" },
    { korean: "회색", english: "gray", pronunciation: "[ɡreɪ]" },
    { korean: "큰", english: "great", pronunciation: "[ɡreɪt]" },
    { korean: "녹색", english: "green", pronunciation: "[ɡrin]" },
    { korean: "땅, 기초", english: "ground", pronunciation: "[ɡraʊnd]" },
    { korean: "단체", english: "group", pronunciation: "[ɡrup]" },
    { korean: "성장하다", english: "grow", pronunciation: "[ɡroʊ]" },
    { korean: "기타(악기)", english: "guitar", pronunciation: "[ɡɪˈtɑr]" },
    { korean: "머리카락", english: "hair", pronunciation: "[hɛr]" },
    { korean: "절반", english: "half", pronunciation: "[hæf]" },
    { korean: "회관, 넓은 방", english: "hall", pronunciation: "[hɔl]" },
    { korean: "햄버거", english: "hamburger", pronunciation: "[ˈhæmbɜrɡər]" },
    { korean: "손", english: "hand", pronunciation: "[hænd]" },
    { korean: "손잡이", english: "handle", pronunciation: "[ˈhændəl]" },
    { korean: "발생하다", english: "happen", pronunciation: "[ˈhæpən]" },
    { korean: "행복한", english: "happy", pronunciation: "[ˈhæpi]" },
    { korean: "단단한, 열심히", english: "hard", pronunciation: "[hɑrd]" },
    { korean: "모자", english: "hat", pronunciation: "[hæt]" },
    { korean: "미워하다", english: "hate", pronunciation: "[heɪt]" },
    { korean: "가지고 있다", english: "have", pronunciation: "[hæv]" },
    { korean: "하나의", english: "a, an", pronunciation: "[eɪ, æn]" },
    { korean: "에 관하여", english: "about", pronunciation: "[əˈbaʊt]" },
    { korean: "을 가로질러", english: "across", pronunciation: "[əˈkrɔs]" },
    { korean: "행동", english: "act", pronunciation: "[ækt]" },
    { korean: "주소", english: "address", pronunciation: "[əˈdrɛs]" },
    { korean: "두려워하여", english: "afraid", pronunciation: "[əˈfreɪd]" },
    { korean: "후에", english: "after", pronunciation: "[ˈæftər]" },
    { korean: "오후", english: "afternoon", pronunciation: "[ˌæftərˈnun]" },
    { korean: "다시", english: "again", pronunciation: "[əˈɡɛn]" },
    { korean: "나이", english: "age", pronunciation: "[eɪdʒ]" },
    { korean: "전에", english: "ago", pronunciation: "[əˈɡoʊ]" },
    { korean: "공기", english: "air", pronunciation: "[ɛr]" },
    { korean: "공항", english: "airport", pronunciation: "[ˈɛrˌpɔrt]" },
    { korean: "사진첩", english: "album", pronunciation: "[ˈælbəm]" },
    { korean: "모두", english: "all", pronunciation: "[ɔl]" },
    { korean: "을 따라서", english: "along", pronunciation: "[əˈlɔŋ]" },
    { korean: "항상", english: "always", pronunciation: "[ˈɔlweɪz]" },
    { korean: "사이에서", english: "among", pronunciation: "[əˈmʌŋ]" },
    { korean: "그리고", english: "and", pronunciation: "[ænd]" },
    { korean: "성난", english: "angry", pronunciation: "[ˈæŋɡri]" },
    { korean: "동물", english: "animal", pronunciation: "[ˈænɪməl]" },
    { korean: "대답", english: "answer", pronunciation: "[ˈænsər]" },
    { korean: "어떤", english: "any", pronunciation: "[ˈɛni]" },
    { korean: "아파트", english: "apartment", pronunciation: "[əˈpɑrtmənt]" },
    { korean: "사과", english: "apple", pronunciation: "[ˈæpəl]" },
    { korean: "팔", english: "arm", pronunciation: "[ɑrm]" },
    { korean: "주위에", english: "around", pronunciation: "[əˈraʊnd]" },
    { korean: "도착하다", english: "arrive", pronunciation: "[əˈraɪv]" },
    { korean: "같은, 로서", english: "as", pronunciation: "[æz]" },
    { korean: "묻다", english: "ask", pronunciation: "[æsk]" },
    { korean: "에", english: "at", pronunciation: "[æt]" },
    { korean: "이모, 고모", english: "aunt", pronunciation: "[ænt]" },
    { korean: "가을", english: "autumn", pronunciation: "[ˈɔtəm]" },
    { korean: "떨어져", english: "away", pronunciation: "[əˈweɪ]" },
    { korean: "아기", english: "baby", pronunciation: "[ˈbeɪbi]" },
    { korean: "뒤에", english: "back", pronunciation: "[bæk]" },
    { korean: "나쁜", english: "bad", pronunciation: "[bæd]" },
    { korean: "가방", english: "bag", pronunciation: "[bæɡ]" },
    { korean: "공", english: "ball", pronunciation: "[bɔl]" },
    { korean: "풍선", english: "balloon", pronunciation: "[bəˈlun]" },
    { korean: "바나나", english: "banana", pronunciation: "[bəˈnænə]" },
    { korean: "끈, 악단", english: "band", pronunciation: "[bænd]" },
    { korean: "은행", english: "bank", pronunciation: "[bæŋk]" },
    { korean: "기초", english: "base", pronunciation: "[beɪs]" },
    { korean: "바구니", english: "basket", pronunciation: "[ˈbæskɪt]" },
    { korean: "목욕", english: "bath", pronunciation: "[bæθ]" },
    { korean: "이다", english: "be", pronunciation: "[bi]" },
    { korean: "해변", english: "beach", pronunciation: "[biʧ]" },
    { korean: "곰", english: "bear", pronunciation: "[bɛr]" },
    { korean: "아름다움", english: "beautiful", pronunciation: "[ˈbjutɪfəl]" },
    { korean: "때문에", english: "because", pronunciation: "[bɪˈkɔz]" },
    { korean: "되다", english: "become", pronunciation: "[bɪˈkʌm]" },
    { korean: "침대", english: "bed", pronunciation: "[bɛd]" },
    { korean: "전에", english: "before", pronunciation: "[bɪˈfɔr]" },
    { korean: "시작하다", english: "begin", pronunciation: "[bɪˈɡɪn]" },
    { korean: "뒤에", english: "behind", pronunciation: "[bɪˈhaɪnd]" },
    { korean: "종", english: "bell", pronunciation: "[bɛl]" },
    { korean: "아래에", english: "below", pronunciation: "[bɪˈloʊ]" },
    { korean: "긴의자", english: "bench", pronunciation: "[bɛnʧ]" },
    { korean: "곁에", english: "beside", pronunciation: "[bɪˈsaɪd]" },
    { korean: "사이에", english: "between", pronunciation: "[bɪˈtwin]" },
    { korean: "자전거", english: "bicycle", pronunciation: "[ˈbaɪsɪkəl]" },
    { korean: "큰", english: "big", pronunciation: "[bɪɡ]" },
    { korean: "새", english: "bird", pronunciation: "[bɜrd]" },
    { korean: "생일", english: "birthday", pronunciation: "[ˈbɜrθˌdeɪ]" },
    { korean: "검은", english: "black", pronunciation: "[blæk]" },
    { korean: "불다", english: "blow", pronunciation: "[bloʊ]" },
    { korean: "푸른", english: "blue", pronunciation: "[blu]" },
    { korean: "판자", english: "board", pronunciation: "[bɔrd]" },
    { korean: "배", english: "boat", pronunciation: "[boʊt]" },
    { korean: "몸", english: "body", pronunciation: "[ˈbɑdi]" },
    { korean: "책", english: "book", pronunciation: "[bʊk]" },
    { korean: "병", english: "bottle", pronunciation: "[ˈbɑtəl]" },
    { korean: "사발", english: "bowl", pronunciation: "[boʊl]" },
    { korean: "상자", english: "box", pronunciation: "[bɑks]" },
    { korean: "팔", english: "arm", pronunciation: "[ɑrm]" },
    { korean: "주위에", english: "around", pronunciation: "[əˈraʊnd]" },
    { korean: "도착하다", english: "arrive", pronunciation: "[əˈraɪv]" },
    { korean: "같은, 로서", english: "as", pronunciation: "[æz]" },
    { korean: "묻다", english: "ask", pronunciation: "[æsk]" },
    { korean: "에", english: "at", pronunciation: "[æt]" },
    { korean: "이모, 고모", english: "aunt", pronunciation: "[ænt]" },
    { korean: "가을", english: "autumn", pronunciation: "[ˈɔtəm]" },
    { korean: "떨어져", english: "away", pronunciation: "[əˈweɪ]" },
    { korean: "아기", english: "baby", pronunciation: "[ˈbeɪbi]" },
    { korean: "뒤에", english: "back", pronunciation: "[bæk]" },
    { korean: "나쁜", english: "bad", pronunciation: "[bæd]" },
    { korean: "가방", english: "bag", pronunciation: "[bæɡ]" },
    { korean: "공", english: "ball", pronunciation: "[bɔl]" },
    { korean: "풍선", english: "balloon", pronunciation: "[bəˈlun]" },
    { korean: "바나나", english: "banana", pronunciation: "[bəˈnænə]" },
    { korean: "끈, 악단", english: "band", pronunciation: "[bænd]" },
    { korean: "은행", english: "bank", pronunciation: "[bæŋk]" },
    { korean: "기초", english: "base", pronunciation: "[beɪs]" },
    { korean: "바구니", english: "basket", pronunciation: "[ˈbæskɪt]" },
    { korean: "목욕", english: "bath", pronunciation: "[bæθ]" },
    { korean: "이다", english: "be", pronunciation: "[bi]" },
    { korean: "해변", english: "beach", pronunciation: "[biʧ]" },
    { korean: "곰", english: "bear", pronunciation: "[bɛr]" },
    { korean: "아름다움", english: "beautiful", pronunciation: "[ˈbjutɪfəl]" },
    { korean: "때문에", english: "because", pronunciation: "[bɪˈkɔz]" },
    { korean: "되다", english: "become", pronunciation: "[bɪˈkʌm]" },
    { korean: "침대", english: "bed", pronunciation: "[bɛd]" },
    { korean: "전에", english: "before", pronunciation: "[bɪˈfɔr]" },
    { korean: "시작하다", english: "begin", pronunciation: "[bɪˈɡɪn]" },
    { korean: "뒤에", english: "behind", pronunciation: "[bɪˈhaɪnd]" },
    { korean: "종", english: "bell", pronunciation: "[bɛl]" },
    { korean: "아래에", english: "below", pronunciation: "[bɪˈloʊ]" },
    { korean: "긴의자", english: "bench", pronunciation: "[bɛnʧ]" },
    { korean: "곁에", english: "beside", pronunciation: "[bɪˈsaɪd]" },
    { korean: "사이에", english: "between", pronunciation: "[bɪˈtwin]" },
    { korean: "자전거", english: "bicycle", pronunciation: "[ˈbaɪsɪkəl]" },
    { korean: "큰", english: "big", pronunciation: "[bɪɡ]" },
    { korean: "새", english: "bird", pronunciation: "[bɜrd]" },
    { korean: "생일", english: "birthday", pronunciation: "[ˈbɜrθˌdeɪ]" },
    { korean: "검은", english: "black", pronunciation: "[blæk]" },
    { korean: "불다", english: "blow", pronunciation: "[bloʊ]" },
    { korean: "푸른", english: "blue", pronunciation: "[blu]" },
    { korean: "판자", english: "board", pronunciation: "[bɔrd]" },
    { korean: "배", english: "boat", pronunciation: "[boʊt]" },
    { korean: "몸", english: "body", pronunciation: "[ˈbɑdi]" },
    { korean: "책", english: "book", pronunciation: "[bʊk]" },
    { korean: "병", english: "bottle", pronunciation: "[ˈbɑtəl]" },
    { korean: "사발", english: "bowl", pronunciation: "[boʊl]" },
    { korean: "상자", english: "box", pronunciation: "[bɑks]" },
    { korean: "팔", english: "arm", pronunciation: "[ɑrm]" },
    { korean: "주위에", english: "around", pronunciation: "[əˈraʊnd]" },
    { korean: "도착하다", english: "arrive", pronunciation: "[əˈraɪv]" },
    { korean: "같은, 로서", english: "as", pronunciation: "[æz]" },
    { korean: "묻다", english: "ask", pronunciation: "[æsk]" },
    { korean: "에", english: "at", pronunciation: "[æt]" },
    { korean: "이모, 고모", english: "aunt", pronunciation: "[ænt]" },
    { korean: "가을", english: "autumn", pronunciation: "[ˈɔtəm]" },
    { korean: "떨어져", english: "away", pronunciation: "[əˈweɪ]" },
    { korean: "아기", english: "baby", pronunciation: "[ˈbeɪbi]" },
    { korean: "뒤에", english: "back", pronunciation: "[bæk]" },
    { korean: "나쁜", english: "bad", pronunciation: "[bæd]" },
    { korean: "가방", english: "bag", pronunciation: "[bæɡ]" },
    { korean: "공", english: "ball", pronunciation: "[bɔl]" },
    { korean: "풍선", english: "balloon", pronunciation: "[bəˈlun]" },
    { korean: "바나나", english: "banana", pronunciation: "[bəˈnænə]" },
    { korean: "끈, 악단", english: "band", pronunciation: "[bænd]" },
    { korean: "은행", english: "bank", pronunciation: "[bæŋk]" },
    { korean: "기초", english: "base", pronunciation: "[beɪs]" },
    { korean: "바구니", english: "basket", pronunciation: "[ˈbæskɪt]" },
    { korean: "목욕", english: "bath", pronunciation: "[bæθ]" },
    { korean: "이다", english: "be", pronunciation: "[bi]" },
    { korean: "해변", english: "beach", pronunciation: "[biʧ]" },
    { korean: "곰", english: "bear", pronunciation: "[bɛr]" },
    { korean: "아름다움", english: "beautiful", pronunciation: "[ˈbjutɪfəl]" },
    { korean: "때문에", english: "because", pronunciation: "[bɪˈkɔz]" },
    { korean: "되다", english: "become", pronunciation: "[bɪˈkʌm]" },
    { korean: "침대", english: "bed", pronunciation: "[bɛd]" },
    { korean: "전에", english: "before", pronunciation: "[bɪˈfɔr]" },
    { korean: "시작하다", english: "begin", pronunciation: "[bɪˈɡɪn]" },
    { korean: "뒤에", english: "behind", pronunciation: "[bɪˈhaɪnd]" },
    { korean: "종", english: "bell", pronunciation: "[bɛl]" },
    { korean: "아래에", english: "below", pronunciation: "[bɪˈloʊ]" },
    { korean: "긴의자", english: "bench", pronunciation: "[bɛnʧ]" },
    { korean: "곁에", english: "beside", pronunciation: "[bɪˈsaɪd]" },
    { korean: "사이에", english: "between", pronunciation: "[bɪˈtwin]" },
    { korean: "자전거", english: "bicycle", pronunciation: "[ˈbaɪsɪkəl]" },
    { korean: "큰", english: "big", pronunciation: "[bɪɡ]" },
    { korean: "새", english: "bird", pronunciation: "[bɜrd]" },
    { korean: "생일", english: "birthday", pronunciation: "[ˈbɜrθˌdeɪ]" },
    { korean: "검은", english: "black", pronunciation: "[blæk]" },
    { korean: "불다", english: "blow", pronunciation: "[bloʊ]" },
    { korean: "푸른", english: "blue", pronunciation: "[blu]" },
    { korean: "판자", english: "board", pronunciation: "[bɔrd]" },
    { korean: "배", english: "boat", pronunciation: "[boʊt]" },
    { korean: "몸", english: "body", pronunciation: "[ˈbɑdi]" },
    { korean: "책", english: "book", pronunciation: "[bʊk]" },
    { korean: "병", english: "bottle", pronunciation: "[ˈbɑtəl]" },
    { korean: "사발", english: "bowl", pronunciation: "[boʊl]" },
    { korean: "상자", english: "box", pronunciation: "[bɑks]" },
    { korean: "팔", english: "arm", pronunciation: "[ɑrm]" },
    { korean: "주위에", english: "around", pronunciation: "[əˈraʊnd]" },
    { korean: "도착하다", english: "arrive", pronunciation: "[əˈraɪv]" },
    { korean: "같은, 로서", english: "as", pronunciation: "[æz]" },
    { korean: "묻다", english: "ask", pronunciation: "[æsk]" },
    { korean: "에", english: "at", pronunciation: "[æt]" },
    { korean: "이모, 고모", english: "aunt", pronunciation: "[ænt]" },
    { korean: "가을", english: "autumn", pronunciation: "[ˈɔtəm]" },
    { korean: "떨어져", english: "away", pronunciation: "[əˈweɪ]" },
    { korean: "아기", english: "baby", pronunciation: "[ˈbeɪbi]" },
    { korean: "뒤에", english: "back", pronunciation: "[bæk]" },
    { korean: "나쁜", english: "bad", pronunciation: "[bæd]" },
    { korean: "가방", english: "bag", pronunciation: "[bæɡ]" },
    { korean: "공", english: "ball", pronunciation: "[bɔl]" },
    { korean: "풍선", english: "balloon", pronunciation: "[bəˈlun]" },
    { korean: "바나나", english: "banana", pronunciation: "[bəˈnænə]" },
    { korean: "끈, 악단", english: "band", pronunciation: "[bænd]" },
    { korean: "은행", english: "bank", pronunciation: "[bæŋk]" },
    { korean: "기초", english: "base", pronunciation: "[beɪs]" },
    { korean: "바구니", english: "basket", pronunciation: "[ˈbæskɪt]" },
    { korean: "목욕", english: "bath", pronunciation: "[bæθ]" },
    { korean: "이다", english: "be", pronunciation: "[bi]" },
    { korean: "해변", english: "beach", pronunciation: "[biʧ]" },
    { korean: "곰", english: "bear", pronunciation: "[bɛr]" },
    { korean: "아름다움", english: "beautiful", pronunciation: "[ˈbjutɪfəl]" },
    { korean: "때문에", english: "because", pronunciation: "[bɪˈkɔz]" },
    { korean: "되다", english: "become", pronunciation: "[bɪˈkʌm]" },
    { korean: "침대", english: "bed", pronunciation: "[bɛd]" },
    { korean: "전에", english: "before", pronunciation: "[bɪˈfɔr]" },
    { korean: "시작하다", english: "begin", pronunciation: "[bɪˈɡɪn]" },
    { korean: "뒤에", english: "behind", pronunciation: "[bɪˈhaɪnd]" },
    { korean: "종", english: "bell", pronunciation: "[bɛl]" },
    { korean: "아래에", english: "below", pronunciation: "[bɪˈloʊ]" },
    { korean: "긴의자", english: "bench", pronunciation: "[bɛnʧ]" },
    { korean: "곁에", english: "beside", pronunciation: "[bɪˈsaɪd]" },
    { korean: "사이에", english: "between", pronunciation: "[bɪˈtwin]" },
    { korean: "자전거", english: "bicycle", pronunciation: "[ˈbaɪsɪkəl]" },
    { korean: "큰", english: "big", pronunciation: "[bɪɡ]" },
    { korean: "새", english: "bird", pronunciation: "[bɜrd]" },
    { korean: "생일", english: "birthday", pronunciation: "[ˈbɜrθˌdeɪ]" },
    { korean: "검은", english: "black", pronunciation: "[blæk]" },
    { korean: "불다", english: "blow", pronunciation: "[bloʊ]" },
    { korean: "푸른", english: "blue", pronunciation: "[blu]" },
    { korean: "판자", english: "board", pronunciation: "[bɔrd]" },
    { korean: "배", english: "boat", pronunciation: "[boʊt]" },
    { korean: "몸", english: "body", pronunciation: "[ˈbɑdi]" },
    { korean: "책", english: "book", pronunciation: "[bʊk]" },
    { korean: "병", english: "bottle", pronunciation: "[ˈbɑtəl]" },
    { korean: "사발", english: "bowl", pronunciation: "[boʊl]" },
    { korean: "상자", english: "box", pronunciation: "[bɑks]" },
    { korean: "팔", english: "arm", pronunciation: "[ɑrm]" },
    { korean: "주위에", english: "around", pronunciation: "[əˈraʊnd]" },
    { korean: "도착하다", english: "arrive", pronunciation: "[əˈraɪv]" },
    { korean: "같은, 로서", english: "as", pronunciation: "[æz]" },
    { korean: "묻다", english: "ask", pronunciation: "[æsk]" },
    { korean: "에", english: "at", pronunciation: "[æt]" },
    { korean: "이모, 고모", english: "aunt", pronunciation: "[ænt]" },
    { korean: "가을", english: "autumn", pronunciation: "[ˈɔtəm]" },
    { korean: "떨어져", english: "away", pronunciation: "[əˈweɪ]" },
    { korean: "아기", english: "baby", pronunciation: "[ˈbeɪbi]" },
    { korean: "뒤에", english: "back", pronunciation: "[bæk]" },
    { korean: "나쁜", english: "bad", pronunciation: "[bæd]" },
    { korean: "가방", english: "bag", pronunciation: "[bæɡ]" },
    { korean: "공", english: "ball", pronunciation: "[bɔl]" },
    { korean: "풍선", english: "balloon", pronunciation: "[bəˈlun]" },
    { korean: "바나나", english: "banana", pronunciation: "[bəˈnænə]" },
    { korean: "끈, 악단", english: "band", pronunciation: "[bænd]" },
    { korean: "은행", english: "bank", pronunciation: "[bæŋk]" },
    { korean: "기초", english: "base", pronunciation: "[beɪs]" },
    { korean: "바구니", english: "basket", pronunciation: "[ˈbæskɪt]" },
    { korean: "목욕", english: "bath", pronunciation: "[bæθ]" },
    { korean: "이다", english: "be", pronunciation: "[bi]" },
    { korean: "해변", english: "beach", pronunciation: "[biʧ]" },
    { korean: "곰", english: "bear", pronunciation: "[bɛr]" },
    { korean: "아름다움", english: "beautiful", pronunciation: "[ˈbjutɪfəl]" },
    { korean: "때문에", english: "because", pronunciation: "[bɪˈkɔz]" },
    { korean: "되다", english: "become", pronunciation: "[bɪˈkʌm]" },
    { korean: "침대", english: "bed", pronunciation: "[bɛd]" },
    { korean: "전에", english: "before", pronunciation: "[bɪˈfɔr]" },
    { korean: "시작하다", english: "begin", pronunciation: "[bɪˈɡɪn]" },
    { korean: "뒤에", english: "behind", pronunciation: "[bɪˈhaɪnd]" },
    { korean: "종", english: "bell", pronunciation: "[bɛl]" },
    { korean: "아래에", english: "below", pronunciation: "[bɪˈloʊ]" },
    { korean: "긴의자", english: "bench", pronunciation: "[bɛnʧ]" },
    { korean: "곁에", english: "beside", pronunciation: "[bɪˈsaɪd]" },
    { korean: "사이에", english: "between", pronunciation: "[bɪˈtwin]" },
    { korean: "자전거", english: "bicycle", pronunciation: "[ˈbaɪsɪkəl]" },
    { korean: "머리", english: "head", pronunciation: "[hɛd]" },
    { korean: "듣다", english: "hear", pronunciation: "[hɪr]" },
    { korean: "마음, 상징", english: "heart", pronunciation: "[hɑrt]" },
    { korean: "무거운", english: "heavy", pronunciation: "[ˈhɛvi]" },
    { korean: "여보세요", english: "hello", pronunciation: "[həˈloʊ]" },
    { korean: "돕다", english: "help", pronunciation: "[hɛlp]" },
    { korean: "암탉", english: "hen", pronunciation: "[hɛn]" },
    { korean: "여기에서", english: "here", pronunciation: "[hɪr]" },
    { korean: "안녕하세요", english: "hi", pronunciation: "[haɪ]" },
    { korean: "숨기다", english: "hide", pronunciation: "[haɪd]" },
    { korean: "높은", english: "high", pronunciation: "[haɪ]" },
    { korean: "하이킹, 도보여행", english: "hiking", pronunciation: "[ˈhaɪkɪŋ]" },
    { korean: "언덕", english: "hill", pronunciation: "[hɪl]" },
    { korean: "때리다", english: "hit", pronunciation: "[hɪt]" },
    { korean: "잡다", english: "hold", pronunciation: "[hoʊld]" },
    { korean: "구멍", english: "hole", pronunciation: "[hoʊl]" },
    { korean: "휴일", english: "holiday", pronunciation: "[ˈhɑlɪˌdeɪ]" },
    { korean: "집", english: "home", pronunciation: "[hoʊm]" },
    { korean: "희망", english: "hope", pronunciation: "[hoʊp]" },
    { korean: "호스", english: "hose", pronunciation: "[hoʊs]" },
    { korean: "말", english: "horse", pronunciation: "[hɔrs]" },
    { korean: "병원", english: "hospital", pronunciation: "[ˈhɑspɪtəl]" },
    { korean: "뜨거운", english: "hot", pronunciation: "[hɑt]" },
    { korean: "호텔", english: "hotel", pronunciation: "[hoʊˈtɛl]" },
    { korean: "시간", english: "hour", pronunciation: "[ˈaʊər]" },
    { korean: "집", english: "house", pronunciation: "[haʊs]" },
    { korean: "어떻게", english: "how", pronunciation: "[haʊ]" },
    { korean: "백(100)", english: "hundred", pronunciation: "[ˈhʌndrəd]" },
    { korean: "배고픈", english: "hungry", pronunciation: "[ˈhʌŋɡri]" },
    { korean: "서두르다", english: "hurry", pronunciation: "[ˈhɜri]" },
    { korean: "다치게 하다", english: "hurt", pronunciation: "[hɜrt]" },
    { korean: "나", english: "I", pronunciation: "[aɪ]" },
    { korean: "얼음", english: "ice", pronunciation: "[aɪs]" },
    { korean: "생각", english: "idea", pronunciation: "[aɪˈdiə]" },
    { korean: "만약", english: "if", pronunciation: "[ɪf]" },
    { korean: "병든", english: "ill", pronunciation: "[ɪl]" },
    { korean: "속", english: "in", pronunciation: "[ɪn]" },
    { korean: "잉크", english: "ink", pronunciation: "[ɪŋk]" },
    { korean: "흥미", english: "interest", pronunciation: "[ˈɪntrəst]" },
    { korean: "속으로", english: "into", pronunciation: "[ˈɪntu]" },
    { korean: "소개하다", english: "introduce", pronunciation: "[ˌɪntrəˈdus]" },
    { korean: "섬", english: "island", pronunciation: "[ˈaɪlənd]" },
    { korean: "그것", english: "it", pronunciation: "[ɪt]" },
    { korean: "직업", english: "job", pronunciation: "[dʒɑb]" },
    { korean: "가입하다", english: "join", pronunciation: "[dʒɔɪn]" },
    { korean: "주스", english: "juice", pronunciation: "[dʒus]" },
    { korean: "뛰어오르다", english: "jump", pronunciation: "[dʒʌmp]" },
    { korean: "밀림지대", english: "jungle", pronunciation: "[ˈdʒʌŋɡəl]" },
    { korean: "오직, 겨우", english: "just", pronunciation: "[dʒʌst]" },
    { korean: "지키다, 유지하다", english: "keep", pronunciation: "[kip]" },
    { korean: "열쇠", english: "key", pronunciation: "[ki]" },
    { korean: "차다", english: "kick", pronunciation: "[kɪk]" },
    { korean: "아이", english: "kid", pronunciation: "[kɪd]" },
    { korean: "죽이다", english: "kill", pronunciation: "[kɪl]" },
    { korean: "친절한, 종류", english: "kind", pronunciation: "[kaɪnd]" },
    { korean: "왕", english: "king", pronunciation: "[kɪŋ]" },
    { korean: "부엌", english: "kitchen", pronunciation: "[ˈkɪʧən]" },
    { korean: "무릎", english: "knee", pronunciation: "[ni]" },
    { korean: "칼", english: "knife", pronunciation: "[naɪf]" },
    { korean: "두드리다", english: "knock", pronunciation: "[nɑk]" },
    { korean: "알다", english: "know", pronunciation: "[noʊ]" },
    { korean: "숙녀", english: "lady", pronunciation: "[ˈleɪdi]" },
    { korean: "호수", english: "lake", pronunciation: "[leɪk]" },
    { korean: "등불", english: "lamp", pronunciation: "[læmp]" },
    { korean: "땅", english: "land", pronunciation: "[lænd]" },
    { korean: "큰, 넓은", english: "large", pronunciation: "[lɑrdʒ]" },
    { korean: "마지막, 최근", english: "last", pronunciation: "[læst]" },
    { korean: "늦은", english: "late", pronunciation: "[leɪt]" },
    { korean: "웃다", english: "laugh", pronunciation: "[læf]" },
    { korean: "인도하다", english: "lead", pronunciation: "[lid]" },
    { korean: "잎", english: "leaf", pronunciation: "[lif]" },
    { korean: "배우다", english: "learn", pronunciation: "[lɜrn]" },
    { korean: "떠나다", english: "leave", pronunciation: "[liv]" },
    { korean: "왼쪽", english: "left", pronunciation: "[lɛft]" },
    { korean: "다리", english: "leg", pronunciation: "[lɛɡ]" },
    { korean: "학과", english: "lesson", pronunciation: "[ˈlɛsən]" },
    { korean: "허락하다", english: "let", pronunciation: "[lɛt]" },
    { korean: "편지", english: "letter", pronunciation: "[ˈlɛtər]" },
    { korean: "도서관", english: "library", pronunciation: "[ˈlaɪˌbrɛri]" },
    { korean: "눕다, 거짓말하다", english: "lie", pronunciation: "[laɪ]" },
    { korean: "빛", english: "light", pronunciation: "[laɪt]" },
    { korean: "좋아하다", english: "like", pronunciation: "[laɪk]" },
    { korean: "선, 줄", english: "line", pronunciation: "[laɪn]" },
    { korean: "사자", english: "lion", pronunciation: "[ˈlaɪən]" },
    { korean: "입술", english: "lip", pronunciation: "[lɪp]" },
    { korean: "목록", english: "list", pronunciation: "[lɪst]" },
    { korean: "듣다", english: "listen", pronunciation: "[ˈlɪsən]" },
    { korean: "작은", english: "little", pronunciation: "[ˈlɪtəl]" },
    { korean: "살다, 생생한", english: "live", pronunciation: "[lɪv]" },
    { korean: "긴", english: "long", pronunciation: "[lɔŋ]" },
    { korean: "바라보다", english: "look", pronunciation: "[lʊk]" },
    { korean: "잃다", english: "lose", pronunciation: "[luz]" },
    { korean: "많음", english: "lot", pronunciation: "[lɑt]" },
    { korean: "소리가 큰", english: "loud", pronunciation: "[laʊd]" },
    { korean: "사랑하다", english: "love", pronunciation: "[lʌv]" },
    { korean: "낮은", english: "low", pronunciation: "[loʊ]" },
    { korean: "행운", english: "luck", pronunciation: "[lʌk]" },
    { korean: "점심식사", english: "lunch", pronunciation: "[lʌnʧ]" },
    { korean: "아주머니", english: "ma'am", pronunciation: "[mæm]" },
    { korean: "미친", english: "mad", pronunciation: "[mæd]" },
    { korean: "우편", english: "mail", pronunciation: "[meɪl]" },
    { korean: "만들다", english: "make", pronunciation: "[meɪk]" },
    { korean: "사람, 남자", english: "man", pronunciation: "[mæn]" },
    { korean: "많은", english: "many", pronunciation: "[ˈmɛni]" },
    { korean: "지도", english: "map", pronunciation: "[mæp]" },
    { korean: "행진, 3월", english: "march", pronunciation: "[mɑrʧ]" },
    { korean: "상점", english: "market", pronunciation: "[ˈmɑrkɪt]" },
    { korean: "결혼하다", english: "marry", pronunciation: "[ˈmæri]" },
    { korean: "문제", english: "matter", pronunciation: "[ˈmætər]" },
    { korean: "할 수 있다, 5월", english: "may", pronunciation: "[meɪ]" },
    { korean: "고기", english: "meat", pronunciation: "[mit]" },
    { korean: "메달", english: "medal", pronunciation: "[ˈmɛdəl]" },
    { korean: "만나다", english: "meet", pronunciation: "[mit]" },
    { korean: "멜론", english: "melon", pronunciation: "[ˈmɛlən]" },
    { korean: "미터", english: "meter", pronunciation: "[ˈmitər]" },
    { korean: "한가운데", english: "middle", pronunciation: "[ˈmɪdəl]" },
    { korean: "우유", english: "milk", pronunciation: "[mɪlk]" },
    { korean: "100만", english: "million", pronunciation: "[ˈmɪljən]" },
    { korean: "분, 순간", english: "minute", pronunciation: "[ˈmɪnɪt]" },
    { korean: "거울", english: "mirror", pronunciation: "[ˈmɪrər]" },
    { korean: "양, 호칭", english: "Miss", pronunciation: "[mɪs]" },
    { korean: "모형", english: "model", pronunciation: "[ˈmɑdəl]" },
    { korean: "엄마", english: "mom(my)", pronunciation: "[mɑm(i)]" },
    { korean: "돈", english: "money", pronunciation: "[ˈmʌni]" },
    { korean: "원숭이", english: "monkey", pronunciation: "[ˈmʌŋki]" },
    { korean: "달, 개월", english: "month", pronunciation: "[mʌnθ]" },
    { korean: "달", english: "moon", pronunciation: "[mun]" },
    { korean: "아침", english: "morning", pronunciation: "[ˈmɔrnɪŋ]" },
    { korean: "어머니", english: "mother", pronunciation: "[ˈmʌðər]" },
    { korean: "산", english: "mountain", pronunciation: "[ˈmaʊntən]" },
    { korean: "입", english: "mouth", pronunciation: "[maʊθ]" },
    { korean: "움직이다", english: "move", pronunciation: "[muv]" },
    { korean: "영화", english: "movie", pronunciation: "[ˈmuvi]" },
    { korean: "씨", english: "Mr.", pronunciation: "[ˈmɪstər]" },
    { korean: "여사", english: "Mrs.", pronunciation: "[ˈmɪsɪz]" },
    { korean: "많은", english: "much", pronunciation: "[mʌʧ]" },
    { korean: "음악", english: "music", pronunciation: "[ˈmjuzɪk]" },
    { korean: "해야 한다", english: "must", pronunciation: "[mʌst]" },
    { korean: "이름", english: "name", pronunciation: "[neɪm]" },
    { korean: "좁은", english: "narrow", pronunciation: "[ˈnɛroʊ]" },
    { korean: "가까운", english: "near", pronunciation: "[nɪr]" },
    { korean: "목", english: "neck", pronunciation: "[nɛk]" },
    { korean: "필요하다", english: "need", pronunciation: "[nid]" },
    { korean: "결코 ~않다", english: "never", pronunciation: "[ˈnɛvər]" },
    { korean: "새로운", english: "new", pronunciation: "[nu]" },
    { korean: "뉴스", english: "news", pronunciation: "[nuz]" },
    { korean: "다음의", english: "next", pronunciation: "[nɛkst]" },
    { korean: "좋은", english: "nice", pronunciation: "[naɪs]" },
    { korean: "밤", english: "night", pronunciation: "[naɪt]" },
    { korean: "아니다, 없다", english: "no", pronunciation: "[noʊ]" },
    { korean: "소음", english: "noise", pronunciation: "[nɔɪz]" },
    { korean: "북쪽", english: "north", pronunciation: "[nɔrθ]" },
    { korean: "코", english: "nose", pronunciation: "[noʊz]" },
    { korean: "아니다", english: "not", pronunciation: "[nɑt]" },
    { korean: "공책", english: "note", pronunciation: "[noʊt]" },
    { korean: "지금", english: "now", pronunciation: "[naʊ]" },
    { korean: "숫자", english: "number", pronunciation: "[ˈnʌmbər]" },
    { korean: "간호원", english: "nurse", pronunciation: "[nɜrs]" },
    { korean: "~시 정각", english: "o'clock", pronunciation: "[əˈklɑk]" },
    { korean: "~의", english: "of", pronunciation: "[ʌv]" },
    { korean: "떨어진, 끄다", english: "off", pronunciation: "[ɔf]" },
    { korean: "사무실", english: "office", pronunciation: "[ˈɔfəs]" },
    { korean: "흔히, 종종", english: "often", pronunciation: "[ˈɔfən]" },
    { korean: "오!", english: "oh", pronunciation: "[oʊ]" },
    { korean: "기름", english: "oil", pronunciation: "[ɔɪl]" },
    { korean: "좋아", english: "okay(ok)", pronunciation: "[oʊˈkeɪ]" },
    { korean: "늙은", english: "old", pronunciation: "[oʊld]" },
    { korean: "~위에", english: "on", pronunciation: "[ɑn]" },
    { korean: "한번", english: "once", pronunciation: "[wʌns]" },
    { korean: "오직", english: "only", pronunciation: "[ˈoʊnli]" },
    { korean: "열린", english: "open", pronunciation: "[ˈoʊpən]" },
    { korean: "또는", english: "or", pronunciation: "[ɔr]" },
    { korean: "오렌지", english: "orange", pronunciation: "[ˈɔrɪndʒ]" },
    { korean: "그 밖의", english: "other", pronunciation: "[ˈʌðər]" },
    { korean: "밖에", english: "out", pronunciation: "[aʊt]" },
    { korean: "~위쪽에", english: "over", pronunciation: "[ˈoʊvər]" },
    { korean: "쪽", english: "page", pronunciation: "[peɪdʒ]" },
    { korean: "칠하다", english: "paint", pronunciation: "[peɪnt]" },
    { korean: "짝", english: "pair", pronunciation: "[pɛr]" },
    { korean: "바지", english: "pants", pronunciation: "[pænts]" },
    { korean: "종이", english: "paper", pronunciation: "[ˈpeɪpər]" },
    { korean: "용서하다", english: "pardon", pronunciation: "[ˈpɑrdən]" },
    { korean: "부모", english: "parent", pronunciation: "[ˈpɛrənt]" },
    { korean: "공원", english: "park", pronunciation: "[pɑrk]" },
    { korean: "파티", english: "party", pronunciation: "[ˈpɑrti]" },
    { korean: "통과하다", english: "pass", pronunciation: "[pæs]" },
    { korean: "지불하다", english: "pay", pronunciation: "[peɪ]" },
    { korean: "평화", english: "peace", pronunciation: "[pis]" },
    { korean: "배", english: "pear", pronunciation: "[pɛr]" },
    { korean: "펜, 만년필", english: "pen", pronunciation: "[pɛn]" },
    { korean: "연필", english: "pencil", pronunciation: "[ˈpɛnsəl]" },
    { korean: "사람", english: "people", pronunciation: "[ˈpipəl]" },
    { korean: "피아노", english: "piano", pronunciation: "[piˈænoʊ]" },
    { korean: "따다, 골라내다", english: "pick", pronunciation: "[pɪk]" },
    { korean: "소풍", english: "picnic", pronunciation: "[ˈpɪknɪk]" },
    { korean: "그림", english: "picture", pronunciation: "[ˈpɪkʧər]" },
    { korean: "조각", english: "piece", pronunciation: "[pis]" },
    { korean: "돼지", english: "pig", pronunciation: "[pɪɡ]" },
    { korean: "조종사", english: "pilot", pronunciation: "[ˈpaɪlət]" },
    { korean: "핀", english: "pin", pronunciation: "[pɪn]" },
    { korean: "소나무", english: "pine", pronunciation: "[paɪn]" },
    { korean: "분홍", english: "pink", pronunciation: "[pɪŋk]" },
    { korean: "파이프, 판", english: "pipe", pronunciation: "[paɪp]" },
    { korean: "장소", english: "place", pronunciation: "[pleɪs]" },
    { korean: "계획", english: "plan", pronunciation: "[plæn]" },
    { korean: "비행기", english: "plane", pronunciation: "[pleɪn]" },
    { korean: "식물", english: "plant", pronunciation: "[plænt]" },
    { korean: "놀다", english: "play", pronunciation: "[pleɪ]" },
    { korean: "기쁘게 하다, 제발", english: "please", pronunciation: "[pliz]" },
    { korean: "주머니", english: "pocket", pronunciation: "[ˈpɑkɪt]" },
    { korean: "점수, 요점", english: "point", pronunciation: "[pɔɪnt]" },
    { korean: "경찰", english: "police", pronunciation: "[pəˈlis]" },
    { korean: "웅덩이", english: "pool", pronunciation: "[pul]" },
    { korean: "가난한", english: "poor", pronunciation: "[pʊr]" },
    { korean: "기둥, 우편", english: "post", pronunciation: "[poʊst]" },
    { korean: "포스터", english: "poster", pronunciation: "[ˈpoʊstər]" },
    { korean: "감자", english: "potato", pronunciation: "[pəˈteɪtoʊ]" },
    { korean: "연습, 습관", english: "practice", pronunciation: "[ˈpræktɪs]" },
    { korean: "현재, 선물", english: "present", pronunciation: "[ˈprɛzənt]" },
    { korean: "예쁜", english: "pretty", pronunciation: "[ˈprɪti]" },
    { korean: "인쇄하다", english: "print", pronunciation: "[prɪnt]" },
    { korean: "문제", english: "problem", pronunciation: "[ˈprɑbləm]" },
    { korean: "끌다", english: "pull", pronunciation: "[pʊl]" },
    { korean: "밀다", english: "push", pronunciation: "[pʊʃ]" },
    { korean: "놓다", english: "put", pronunciation: "[pʊt]" },
    { korean: "여왕", english: "queen", pronunciation: "[kwin]" },
    { korean: "질문", english: "question", pronunciation: "[ˈkwɛsʧən]" },
    { korean: "빠른", english: "quick", pronunciation: "[kwɪk]" },
    { korean: "조용한", english: "quiet", pronunciation: "[ˈkwaɪət]" },
    { korean: "라디오", english: "radio", pronunciation: "[ˈreɪdiˌoʊ]" },
    { korean: "비", english: "rain", pronunciation: "[reɪn]" },
    { korean: "무지개", english: "rainbow", pronunciation: "[ˈreɪnˌboʊ]" },
    { korean: "읽다", english: "read", pronunciation: "[rid]" },
    { korean: "준비가 된", english: "ready", pronunciation: "[ˈrɛdi]" },
    { korean: "실제하는", english: "real", pronunciation: "[ril]" },
    { korean: "기록하다", english: "record", pronunciation: "[ˈrɛkərd]" },
    { korean: "빨강", english: "red", pronunciation: "[rɛd]" },
];


let currentWordIndex = 0;
let pronounceInterval;
let synth = window.speechSynthesis;
let autoPlayInterval;

function updateWord() {
    document.getElementById('word-korean').innerText = words[currentWordIndex].korean;
    document.getElementById('word-english').innerText = words[currentWordIndex].english;
    document.getElementById('word-pronunciation').innerText = words[currentWordIndex].pronunciation;
}

function pronounceWord(times, callback) {
    let count = 0;

    function speak() {
        if (count < times) {
            let koreanUtterance = new SpeechSynthesisUtterance(words[currentWordIndex].korean);
            koreanUtterance.lang = 'ko-KR'; // 한국어 발음 설정
            koreanUtterance.rate = 1; // 발음 속도 설정 (1배 빠르게)

            let englishUtterance = new SpeechSynthesisUtterance(words[currentWordIndex].english);
            englishUtterance.lang = 'en-US'; // 영어 발음 설정
            englishUtterance.rate = 1; // 발음 속도 설정 (1배 빠르게)

            koreanUtterance.onend = () => {
                synth.speak(englishUtterance);
            };

            englishUtterance.onend = () => {
                count++;
                if (count < times) {
                    speak();
                } else if (callback) {
                    callback();
                }
            };

            synth.speak(koreanUtterance);
        }
    }

    speak();
}

function stopPronouncing() {
    clearInterval(pronounceInterval);
    clearInterval(autoPlayInterval);
    synth.cancel();
}

function nextWord() {
    currentWordIndex = (currentWordIndex + 1) % words.length;
    updateWord();
    pronounceWord(1);
}

function autoPlay() {
    stopPronouncing();
    currentWordIndex = 0; // 처음부터 시작
    autoPlayInterval = setInterval(() => {
        updateWord();
        pronounceWord(1, () => {
            currentWordIndex++;
            if (currentWordIndex >= words.length) {
                currentWordIndex = 0; // 끝에 도달하면 처음으로 돌아가기
            }
        });
    }, 8000); // 6초마다 다음 단어로 넘어가고 발음 (발음 시간 3초 + 대기 시간 3초)
}

updateWord();

// 단어 목록을 화면에 표시하는 함수
function showWordList() {
    const wordList = document.getElementById('word-list');
    words.forEach(word => {
        const listItem = document.createElement('li');
        listItem.classList.add('list-group-item');
        listItem.innerHTML = `<strong>${word.korean}</strong><br>${word.english}<em><br>${word.pronunciation}</em><br><br>`;
        wordList.appendChild(listItem);
    });
}

document.addEventListener('DOMContentLoaded', () => {
    updateWord();
    showWordList(); // 페이지 로드 시 단어 목록 표시
});
