const words = [
    { korean: "비교하다", english: "Compare", pronunciation: "[kəmˈpɛər]" },
    { korean: "설명하다", english: "Explain", pronunciation: "[ɪkˈspleɪn]" },
    { korean: "제안하다", english: "Suggest", pronunciation: "[səˈdʒɛst]" },
    { korean: "개발하다", english: "Develop", pronunciation: "[dɪˈvɛləp]" },
    { korean: "지지하다", english: "Support", pronunciation: "[səˈpɔːrt]" },
    { korean: "기대하다", english: "Expect", pronunciation: "[ɪkˈspɛkt]" },
    { korean: "선택하다", english: "Choose", pronunciation: "[tʃuːz]" },
    { korean: "의견을 말하다", english: "Express", pronunciation: "[ɪkˈsprɛs]" },
    { korean: "계획하다", english: "Plan", pronunciation: "[plæn]" },
    { korean: "확인하다", english: "Confirm", pronunciation: "[kənˈfɜːrm]" },
    { korean: "조사하다", english: "Investigate", pronunciation: "[ɪnˈvɛstəɡeɪt]" },
    { korean: "준비하다", english: "Prepare", pronunciation: "[prɪˈpɛər]" },
    { korean: "실행하다", english: "Implement", pronunciation: "[ˈɪmplɪmɛnt]" },
    { korean: "분석하다", english: "Analyze", pronunciation: "[ˈænəˌlaɪz]" },
    { korean: "설계하다", english: "Design", pronunciation: "[dɪˈzaɪn]" },
    { korean: "평가하다", english: "Evaluate", pronunciation: "[ɪˈvæljueɪt]" },
    { korean: "기록하다", english: "Record", pronunciation: "[ˈrɛkərd]" },
    { korean: "연구하다", english: "Research", pronunciation: "[rɪˈsɜːrtʃ]" },
    { korean: "감사하다", english: "Appreciate", pronunciation: "[əˈpriːʃieɪt]" },
    { korean: "설득하다", english: "Persuade", pronunciation: "[pərˈsweɪd]" },
    // 여기에 추가로 480개의 단어를 입력하십시오.
    { korean: "관리하다", english: "Manage", pronunciation: "[ˈmænɪdʒ]" },
    { korean: "저장하다", english: "Store", pronunciation: "[stɔːr]" },
    { korean: "비평하다", english: "Criticize", pronunciation: "[ˈkrɪtɪˌsaɪz]" },
    { korean: "조언하다", english: "Advise", pronunciation: "[ədˈvaɪz]" },
    { korean: "동의하다", english: "Agree", pronunciation: "[əˈɡriː]" },
    { korean: "포함하다", english: "Include", pronunciation: "[ɪnˈkluːd]" },
    { korean: "기록하다", english: "Record", pronunciation: "[ˈrɛkərd]" },
    { korean: "결정하다", english: "Decide", pronunciation: "[dɪˈsaɪd]" },
    { korean: "조정하다", english: "Adjust", pronunciation: "[əˈdʒʌst]" },
    { korean: "받다", english: "Receive", pronunciation: "[rɪˈsiːv]" },
    { korean: "초대하다", english: "Invite", pronunciation: "[ɪnˈvaɪt]" },
    { korean: "경험하다", english: "Experience", pronunciation: "[ɪkˈspɪəriəns]" },
    { korean: "정리하다", english: "Organize", pronunciation: "[ˈɔːɡəˌnaɪz]" },
    { korean: "진행하다", english: "Proceed", pronunciation: "[prəˈsiːd]" },
    { korean: "보호하다", english: "Protect", pronunciation: "[prəˈtɛkt]" },
    { korean: "기부하다", english: "Donate", pronunciation: "[ˈdoʊneɪt]" },
    { korean: "달성하다", english: "Achieve", pronunciation: "[əˈtʃiːv]" },
    { korean: "구매하다", english: "Purchase", pronunciation: "[ˈpɜːrtʃəs]" },
    { korean: "해결하다", english: "Resolve", pronunciation: "[rɪˈzɒlv]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "개선하다", english: "Improve", pronunciation: "[ɪmˈpruːv]" },
    { korean: "작성하다", english: "Draft", pronunciation: "[dræft]" },
    { korean: "설립하다", english: "Establish", pronunciation: "[ɪˈstæblɪʃ]" },
    { korean: "협력하다", english: "Collaborate", pronunciation: "[kəˈlæbəˌreɪt]" },
    { korean: "명령하다", english: "Command", pronunciation: "[kəˈmænd]" },
    { korean: "준수하다", english: "Comply", pronunciation: "[kəmˈplaɪ]" },
    { korean: "대처하다", english: "Cope", pronunciation: "[koʊp]" },
    { korean: "고려하다", english: "Consider", pronunciation: "[kənˈsɪdər]" },
    { korean: "관찰하다", english: "Observe", pronunciation: "[əbˈzɜːrv]" },
    { korean: "이끌다", english: "Lead", pronunciation: "[liːd]" },
    { korean: "계산하다", english: "Calculate", pronunciation: "[ˈkælkjəˌleɪt]" },
    { korean: "해석하다", english: "Interpret", pronunciation: "[ɪnˈtɜːrprɪt]" },
    { korean: "증명하다", english: "Prove", pronunciation: "[pruːv]" },
    { korean: "요구하다", english: "Demand", pronunciation: "[dɪˈmænd]" },
    { korean: "상기하다", english: "Recall", pronunciation: "[rɪˈkɔːl]" },
    { korean: "보고하다", english: "Report", pronunciation: "[rɪˈpɔːrt]" },
    { korean: "허락하다", english: "Permit", pronunciation: "[pərˈmɪt]" },
    { korean: "제한하다", english: "Restrict", pronunciation: "[rɪˈstrɪkt]" },
    { korean: "조작하다", english: "Manipulate", pronunciation: "[məˈnɪpjəˌleɪt]" },
    { korean: "보상하다", english: "Compensate", pronunciation: "[ˈkɑːmpənˌseɪt]" },
    { korean: "모으다", english: "Collect", pronunciation: "[kəˈlɛkt]" },
    { korean: "기록하다", english: "Record", pronunciation: "[ˈrɛkərd]" },
    { korean: "유지하다", english: "Maintain", pronunciation: "[meɪnˈteɪn]" },
    { korean: "확대하다", english: "Expand", pronunciation: "[ɪkˈspænd]" },
    { korean: "분배하다", english: "Distribute", pronunciation: "[dɪˈstrɪbjut]" },
    { korean: "통제하다", english: "Control", pronunciation: "[kənˈtroʊl]" },
    { korean: "처리하다", english: "Handle", pronunciation: "[ˈhændəl]" },
    { korean: "거래하다", english: "Trade", pronunciation: "[treɪd]" },
    { korean: "시도하다", english: "Attempt", pronunciation: "[əˈtɛmpt]" },
    { korean: "알리다", english: "Inform", pronunciation: "[ɪnˈfɔːrm]" },
    { korean: "명심하다", english: "Bear in mind", pronunciation: "[ber ɪn maɪnd]" },
    { korean: "논쟁하다", english: "Argue", pronunciation: "[ˈɑːrɡju]" },
    { korean: "수리하다", english: "Repair", pronunciation: "[rɪˈpɛər]" },
    { korean: "거부하다", english: "Refuse", pronunciation: "[rɪˈfjuz]" },
    { korean: "배려하다", english: "Consider", pronunciation: "[kənˈsɪdər]" },
    { korean: "설치하다", english: "Install", pronunciation: "[ɪnˈstɔːl]" },
    { korean: "달성하다", english: "Attain", pronunciation: "[əˈteɪn]" },
    { korean: "혼합하다", english: "Combine", pronunciation: "[kəmˈbaɪn]" },
    { korean: "지속하다", english: "Sustain", pronunciation: "[səˈsteɪn]" },
    { korean: "지속하다", english: "Persist", pronunciation: "[pərˈsɪst]" },
    { korean: "증진하다", english: "Enhance", pronunciation: "[ɪnˈhæns]" },
    { korean: "제공하다", english: "Provide", pronunciation: "[prəˈvaɪd]" },
    { korean: "발생하다", english: "Occur", pronunciation: "[əˈkɜːr]" },
    { korean: "출발하다", english: "Depart", pronunciation: "[dɪˈpɑːrt]" },
    { korean: "복사하다", english: "Copy", pronunciation: "[ˈkɒpi]" },
    { korean: "분석하다", english: "Analyze", pronunciation: "[ˈænəˌlaɪz]" },
    { korean: "간주하다", english: "Regard", pronunciation: "[rɪˈɡɑːrd]" },
    { korean: "제공하다", english: "Offer", pronunciation: "[ˈɔːfər]" },
    { korean: "가정하다", english: "Assume", pronunciation: "[əˈsuːm]" },
    { korean: "대답하다", english: "Answer", pronunciation: "[ˈænsər]" },
    { korean: "보장하다", english: "Guarantee", pronunciation: "[ˌɡærənˈtiː]" },
    { korean: "명시하다", english: "Specify", pronunciation: "[ˈspɛsɪˌfaɪ]" },
    { korean: "수행하다", english: "Perform", pronunciation: "[pərˈfɔːrm]" },
    { korean: "증거를 제공하다", english: "Substantiate", pronunciation: "[səbˈstænʃieɪt]" },
    { korean: "관리하다", english: "Administer", pronunciation: "[ədˈmɪnɪstər]" },
    { korean: "완화하다", english: "Mitigate", pronunciation: "[ˈmɪtɪˌɡeɪt]" },
    { korean: "시작하다", english: "Commence", pronunciation: "[kəˈmɛns]" },
    { korean: "보존하다", english: "Preserve", pronunciation: "[prɪˈzɜːrv]" },
    { korean: "회피하다", english: "Avoid", pronunciation: "[əˈvɔɪd]" },
    { korean: "확보하다", english: "Secure", pronunciation: "[sɪˈkjʊr]" },
    { korean: "거부하다", english: "Reject", pronunciation: "[rɪˈdʒɛkt]" },
    { korean: "지연하다", english: "Delay", pronunciation: "[dɪˈleɪ]" },
    { korean: "제외하다", english: "Exclude", pronunciation: "[ɪkˈskluːd]" },
    { korean: "허용하다", english: "Allow", pronunciation: "[əˈlaʊ]" },
    { korean: "비난하다", english: "Condemn", pronunciation: "[kənˈdɛm]" },
    { korean: "진행하다", english: "Progress", pronunciation: "[ˈprɑːɡrɛs]" },
    { korean: "단축하다", english: "Shorten", pronunciation: "[ˈʃɔːrtn]" },
    { korean: "논쟁하다", english: "Debate", pronunciation: "[dɪˈbeɪt]" },
    { korean: "수축하다", english: "Contract", pronunciation: "[ˈkɒntrækt]" },
    { korean: "중재하다", english: "Mediate", pronunciation: "[ˈmiːdieɪt]" },
    { korean: "흡수하다", english: "Absorb", pronunciation: "[əbˈzɔːrb]" },
    { korean: "반영하다", english: "Reflect", pronunciation: "[rɪˈflɛkt]" },
    { korean: "기록하다", english: "Record", pronunciation: "[ˈrɛkərd]" },
    { korean: "번역하다", english: "Translate", pronunciation: "[trænzˈleɪt]" },
    { korean: "제기하다", english: "Raise", pronunciation: "[reɪz]" },
    { korean: "분할하다", english: "Divide", pronunciation: "[dɪˈvaɪd]" },
    { korean: "제안하다", english: "Propose", pronunciation: "[prəˈpoʊz]" },
    { korean: "예측하다", english: "Forecast", pronunciation: "[ˈfɔːrkæst]" },
    { korean: "일으키다", english: "Generate", pronunciation: "[ˈdʒɛnəˌreɪt]" },
    { korean: "배분하다", english: "Allocate", pronunciation: "[ˈæləˌkeɪt]" },
    { korean: "발견하다", english: "Discover", pronunciation: "[dɪˈskʌvər]" },
    { korean: "강조하다", english: "Emphasize", pronunciation: "[ˈɛmfəˌsaɪz]" },
    { korean: "갱신하다", english: "Renew", pronunciation: "[rɪˈnjuː]" },
    { korean: "수익을 올리다", english: "Profit", pronunciation: "[ˈprɒfɪt]" },
    { korean: "축소하다", english: "Reduce", pronunciation: "[rɪˈdjuːs]" },
    { korean: "중단하다", english: "Suspend", pronunciation: "[səˈspɛnd]" },
    { korean: "획득하다", english: "Obtain", pronunciation: "[əbˈteɪn]" },
    { korean: "조달하다", english: "Procure", pronunciation: "[prəˈkjʊər]" },
    { korean: "계속하다", english: "Continue", pronunciation: "[kənˈtɪnjuː]" },
    { korean: "감독하다", english: "Supervise", pronunciation: "[ˈsuːpərˌvaɪz]" },
    { korean: "입력하다", english: "Input", pronunciation: "[ˈɪnˌpʊt]" },
    { korean: "수정하다", english: "Revise", pronunciation: "[rɪˈvaɪz]" },
    { korean: "실행하다", english: "Execute", pronunciation: "[ˈɛksɪˌkjuːt]" },
    { korean: "확장하다", english: "Enlarge", pronunciation: "[ɪnˈlɑːrdʒ]" },
    { korean: "지연하다", english: "Postpone", pronunciation: "[poʊstˈpoʊn]" },
    { korean: "채용하다", english: "Recruit", pronunciation: "[rɪˈkruːt]" },
    { korean: "기준에 맞추다", english: "Standardize", pronunciation: "[ˈstændərˌdaɪz]" },
    { korean: "계산하다", english: "Compute", pronunciation: "[kəmˈpjuːt]" },
    { korean: "체크하다", english: "Check", pronunciation: "[tʃɛk]" },
    { korean: "연장하다", english: "Extend", pronunciation: "[ɪkˈstɛnd]" },
    { korean: "예정하다", english: "Schedule", pronunciation: "[ˈskɛdʒʊl]" },
    { korean: "지원하다", english: "Support", pronunciation: "[səˈpɔːrt]" },
    { korean: "배달하다", english: "Deliver", pronunciation: "[dɪˈlɪvər]" },
    { korean: "확인하다", english: "Verify", pronunciation: "[ˈvɛrəˌfaɪ]" },
    { korean: "이행하다", english: "Fulfill", pronunciation: "[fʊlˈfɪl]" },
    { korean: "취소하다", english: "Cancel", pronunciation: "[ˈkænsəl]" },
    { korean: "다루다", english: "Handle", pronunciation: "[ˈhændəl]" },
    { korean: "관찰하다", english: "Observe", pronunciation: "[əbˈzɜːrv]" },
    { korean: "요청하다", english: "Request", pronunciation: "[rɪˈkwɛst]" },
    { korean: "등록하다", english: "Register", pronunciation: "[ˈrɛdʒɪstər]" },
    { korean: "검사하다", english: "Inspect", pronunciation: "[ɪnˈspɛkt]" },
    { korean: "제출하다", english: "Submit", pronunciation: "[səbˈmɪt]" },
    { korean: "합의하다", english: "Agree", pronunciation: "[əˈɡriː]" },
    { korean: "재검토하다", english: "Review", pronunciation: "[rɪˈvjuː]" },
    { korean: "비평하다", english: "Critique", pronunciation: "[krɪˈtik]" },
    { korean: "보관하다", english: "Store", pronunciation: "[stɔːr]" },
    { korean: "기대하다", english: "Anticipate", pronunciation: "[ænˈtɪsɪˌpeɪt]" },
    { korean: "축하하다", english: "Celebrate", pronunciation: "[ˈsɛləˌbreɪt]" },
    { korean: "동반하다", english: "Accompany", pronunciation: "[əˈkʌmpəni]" },
    { korean: "서명하다", english: "Sign", pronunciation: "[saɪn]" },
    { korean: "대비하다", english: "Prepare", pronunciation: "[prɪˈpɛər]" },
    { korean: "보장하다", english: "Ensure", pronunciation: "[ɪnˈʃʊr]" },
    { korean: "알리다", english: "Notify", pronunciation: "[ˈnoʊtəˌfaɪ]" },
    { korean: "확장하다", english: "Expand", pronunciation: "[ɪkˈspænd]" },
    { korean: "정렬하다", english: "Align", pronunciation: "[əˈlaɪn]" },
    { korean: "연구하다", english: "Research", pronunciation: "[rɪˈsɜːrtʃ]" },
    { korean: "발견하다", english: "Detect", pronunciation: "[dɪˈtɛkt]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "방해하다", english: "Disrupt", pronunciation: "[dɪsˈrʌpt]" },
    { korean: "확인하다", english: "Ascertain", pronunciation: "[ˌæsərˈteɪn]" },
    { korean: "정의하다", english: "Define", pronunciation: "[dɪˈfaɪn]" },
    { korean: "보호하다", english: "Protect", pronunciation: "[prəˈtɛkt]" },
    { korean: "작성하다", english: "Draft", pronunciation: "[dræft]" },
    { korean: "조사하다", english: "Examine", pronunciation: "[ɪɡˈzæmɪn]" },
    { korean: "탐색하다", english: "Explore", pronunciation: "[ɪkˈsplɔːr]" },
    { korean: "지정하다", english: "Assign", pronunciation: "[əˈsaɪn]" },
    { korean: "감독하다", english: "Oversee", pronunciation: "[ˌoʊvərˈsiː]" },
    { korean: "개선하다", english: "Enhance", pronunciation: "[ɪnˈhæns]" },
    { korean: "도입하다", english: "Introduce", pronunciation: "[ˌɪntrəˈdus]" },
    { korean: "예측하다", english: "Predict", pronunciation: "[prɪˈdɪkt]" },
    { korean: "복구하다", english: "Restore", pronunciation: "[rɪˈstɔːr]" },
    { korean: "포착하다", english: "Capture", pronunciation: "[ˈkæptʃər]" },
    { korean: "발표하다", english: "Announce", pronunciation: "[əˈnaʊns]" },
    { korean: "경고하다", english: "Warn", pronunciation: "[wɔːrn]" },
    { korean: "통합하다", english: "Integrate", pronunciation: "[ˈɪntɪˌɡreɪt]" },
    { korean: "결정하다", english: "Determine", pronunciation: "[dɪˈtɜːrmɪn]" },
    { korean: "복사하다", english: "Duplicate", pronunciation: "[ˈdjuːplɪˌkeɪt]" },
    { korean: "협상하다", english: "Negotiate", pronunciation: "[nɪˈɡoʊʃieɪt]" },
    { korean: "표현하다", english: "Convey", pronunciation: "[kənˈveɪ]" },
    { korean: "수용하다", english: "Accommodate", pronunciation: "[əˈkɑːməˌdeɪt]" },
    { korean: "강조하다", english: "Highlight", pronunciation: "[ˈhaɪˌlaɪt]" },
    { korean: "출판하다", english: "Publish", pronunciation: "[ˈpʌblɪʃ]" },
    { korean: "감소하다", english: "Diminish", pronunciation: "[dɪˈmɪnɪʃ]" },
    { korean: "유지하다", english: "Sustain", pronunciation: "[səˈsteɪn]" },
    { korean: "조정하다", english: "Moderate", pronunciation: "[ˈmɒdəˌreɪt]" },
    { korean: "개발하다", english: "Cultivate", pronunciation: "[ˈkʌltɪˌveɪt]" },
    { korean: "주장하다", english: "Assert", pronunciation: "[əˈsɜːrt]" },
    { korean: "논의하다", english: "Discuss", pronunciation: "[dɪˈskʌs]" },
    { korean: "해석하다", english: "Interpret", pronunciation: "[ɪnˈtɜːrprɪt]" },
    { korean: "부여하다", english: "Grant", pronunciation: "[ɡrænt]" },
    { korean: "입증하다", english: "Demonstrate", pronunciation: "[ˈdɛmənˌstreɪt]" },
    { korean: "억제하다", english: "Inhibit", pronunciation: "[ɪnˈhɪbɪt]" },
    { korean: "감사하다", english: "Appreciate", pronunciation: "[əˈpriːʃieɪt]" },
    { korean: "저지하다", english: "Prevent", pronunciation: "[prɪˈvɛnt]" },
    { korean: "촉진하다", english: "Facilitate", pronunciation: "[fəˈsɪlɪˌteɪt]" },
    { korean: "보완하다", english: "Supplement", pronunciation: "[ˈsʌplɪˌmɛnt]" },
    { korean: "이루다", english: "Achieve", pronunciation: "[əˈtʃiːv]" },
    { korean: "전달하다", english: "Transmit", pronunciation: "[trænzˈmɪt]" },
    { korean: "인식하다", english: "Perceive", pronunciation: "[pərˈsiːv]" },
    { korean: "차별하다", english: "Discriminate", pronunciation: "[dɪˈskrɪməˌneɪt]" },
    { korean: "격려하다", english: "Encourage", pronunciation: "[ɪnˈkɜːrɪdʒ]" },
    { korean: "제기하다", english: "Raise", pronunciation: "[reɪz]" },
    { korean: "강화하다", english: "Reinforce", pronunciation: "[ˌriɪnˈfɔrs]" },
    { korean: "기획하다", english: "Plan", pronunciation: "[plæn]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "주장하다", english: "Claim", pronunciation: "[kleɪm]" },
    { korean: "도움이 되다", english: "Benefit", pronunciation: "[ˈbɛnɪfɪt]" },
    { korean: "개정하다", english: "Amend", pronunciation: "[əˈmɛnd]" },
    { korean: "제출하다", english: "Submit", pronunciation: "[səbˈmɪt]" },
    { korean: "분류하다", english: "Classify", pronunciation: "[ˈklæsɪˌfaɪ]" },
    { korean: "관리하다", english: "Administer", pronunciation: "[ədˈmɪnɪstər]" },
    { korean: "취득하다", english: "Acquire", pronunciation: "[əˈkwaɪər]" },
    { korean: "통제하다", english: "Regulate", pronunciation: "[ˈrɛɡjəˌleɪt]" },
    { korean: "복구하다", english: "Rehabilitate", pronunciation: "[ˌriəˈbɪlɪˌteɪt]" },
    { korean: "평가하다", english: "Appraise", pronunciation: "[əˈpreɪz]" },
    { korean: "증명하다", english: "Verify", pronunciation: "[ˈvɛrəˌfaɪ]" },
    { korean: "분리하다", english: "Isolate", pronunciation: "[ˈaɪsəˌleɪt]" },
    { korean: "인정하다", english: "Acknowledge", pronunciation: "[ækˈnɒlɪdʒ]" },
    { korean: "이행하다", english: "Implement", pronunciation: "[ˈɪmplɪmɛnt]" },
    { korean: "요구하다", english: "Require", pronunciation: "[rɪˈkwaɪər]" },
    { korean: "기여하다", english: "Contribute", pronunciation: "[kənˈtrɪbjut]" },
    { korean: "요약하다", english: "Summarize", pronunciation: "[ˈsʌməˌraɪz]" },
    { korean: "최소화하다", english: "Minimize", pronunciation: "[ˈmɪnɪˌmaɪz]" },
    { korean: "최대화하다", english: "Maximize", pronunciation: "[ˈmæksɪˌmaɪz]" },
    { korean: "예방하다", english: "Prevent", pronunciation: "[prɪˈvɛnt]" },
    { korean: "대응하다", english: "Respond", pronunciation: "[rɪˈspɒnd]" },
    { korean: "변경하다", english: "Alter", pronunciation: "[ˈɔltər]" },
    { korean: "고수하다", english: "Adhere", pronunciation: "[ədˈhɪər]" },
    { korean: "협력하다", english: "Collaborate", pronunciation: "[kəˈlæbəˌreɪt]" },
    { korean: "반영하다", english: "Reflect", pronunciation: "[rɪˈflɛkt]" },
    { korean: "처리하다", english: "Process", pronunciation: "[ˈprɑsɛs]" },
    { korean: "요구하다", english: "Demand", pronunciation: "[dɪˈmænd]" },
    { korean: "지원하다", english: "Support", pronunciation: "[səˈpɔrt]" },
    { korean: "협상하다", english: "Negotiate", pronunciation: "[nɪˈɡoʊʃiˌeɪt]" },
    { korean: "전환하다", english: "Convert", pronunciation: "[kənˈvɜrt]" },
    { korean: "가정하다", english: "Assume", pronunciation: "[əˈsum]" },
    { korean: "고려하다", english: "Consider", pronunciation: "[kənˈsɪdər]" },
    { korean: "지속하다", english: "Persist", pronunciation: "[pərˈsɪst]" },
    { korean: "공급하다", english: "Supply", pronunciation: "[səˈplaɪ]" },
    { korean: "자문하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "합리화하다", english: "Rationalize", pronunciation: "[ˈræʃənəˌlaɪz]" },
    { korean: "유지하다", english: "Maintain", pronunciation: "[meɪnˈteɪn]" },
    { korean: "참조하다", english: "Refer", pronunciation: "[rɪˈfɜr]" },
    { korean: "조정하다", english: "Adjust", pronunciation: "[əˈdʒʌst]" },
    { korean: "지속하다", english: "Endure", pronunciation: "[ɛnˈdʊr]" },
    { korean: "접근하다", english: "Approach", pronunciation: "[əˈproʊʧ]" },
    { korean: "확보하다", english: "Secure", pronunciation: "[sɪˈkjʊr]" },
    { korean: "변경하다", english: "Modify", pronunciation: "[ˈmɑdəˌfaɪ]" },
    { korean: "명확히 하다", english: "Clarify", pronunciation: "[ˈklærəˌfaɪ]" },
    { korean: "보완하다", english: "Enhance", pronunciation: "[ɪnˈhæns]" },
    { korean: "조절하다", english: "Regulate", pronunciation: "[ˈrɛɡjəˌleɪt]" },
    { korean: "생산하다", english: "Generate", pronunciation: "[ˈʤɛnəˌreɪt]" },
    { korean: "조사하다", english: "Investigate", pronunciation: "[ɪnˈvɛstəˌɡeɪt]" },
    { korean: "보장하다", english: "Guarantee", pronunciation: "[ˌɡærənˈti]" },
    { korean: "상당하다", english: "Correspond", pronunciation: "[ˌkɔrəˈspɑnd]" },
    { korean: "운영하다", english: "Operate", pronunciation: "[ˈɑpəˌreɪt]" },
    { korean: "제시하다", english: "Present", pronunciation: "[prɪˈzɛnt]" },
    { korean: "설립하다", english: "Establish", pronunciation: "[ɪˈstæblɪʃ]" },
    { korean: "연구하다", english: "Research", pronunciation: "[rɪˈsɜrtʃ]" },
    { korean: "조정하다", english: "Coordinate", pronunciation: "[koʊˈɔrdəˌneɪt]" },
    { korean: "요청하다", english: "Request", pronunciation: "[rɪˈkwɛst]" },
    { korean: "지속하다", english: "Sustain", pronunciation: "[səˈsteɪn]" },
    { korean: "통합하다", english: "Integrate", pronunciation: "[ˈɪntəˌɡreɪt]" },
    { korean: "고려하다", english: "Consider", pronunciation: "[kənˈsɪdər]" },
    { korean: "포착하다", english: "Capture", pronunciation: "[ˈkæptʃər]" },
    { korean: "논의하다", english: "Discuss", pronunciation: "[dɪˈskʌs]" },
    { korean: "관리하다", english: "Manage", pronunciation: "[ˈmænɪdʒ]" },
    { korean: "검토하다", english: "Review", pronunciation: "[rɪˈvju]" },
    { korean: "해결하다", english: "Resolve", pronunciation: "[rɪˈzɑlv]" },
    { korean: "예방하다", english: "Prevent", pronunciation: "[prɪˈvɛnt]" },
    { korean: "수행하다", english: "Perform", pronunciation: "[pərˈfɔrm]" },
    { korean: "준비하다", english: "Prepare", pronunciation: "[prɪˈpɛr]" },
    { korean: "확장하다", english: "Expand", pronunciation: "[ɪkˈspænd]" },
    { korean: "조사하다", english: "Examine", pronunciation: "[ɪɡˈzæmɪn]" },
    { korean: "관리하다", english: "Supervise", pronunciation: "[ˈsuprəˌvaɪz]" },
    { korean: "개발하다", english: "Develop", pronunciation: "[dɪˈvɛləp]" },
    { korean: "연구하다", english: "Investigate", pronunciation: "[ɪnˈvɛstəˌɡeɪt]" },
    { korean: "제공하다", english: "Provide", pronunciation: "[prəˈvaɪd]" },
    { korean: "시작하다", english: "Commence", pronunciation: "[kəˈmɛns]" },
    { korean: "지정하다", english: "Designate", pronunciation: "[ˈdɛzɪɡˌneɪt]" },
    { korean: "시행하다", english: "Implement", pronunciation: "[ˈɪmpləˌmɛnt]" },
    { korean: "기대하다", english: "Anticipate", pronunciation: "[ænˈtɪsɪˌpeɪt]" },
    { korean: "강조하다", english: "Emphasize", pronunciation: "[ˈɛmfəˌsaɪz]" },
    { korean: "통제하다", english: "Control", pronunciation: "[kənˈtroʊl]" },
    { korean: "검사하다", english: "Inspect", pronunciation: "[ɪnˈspɛkt]" },
    { korean: "분석하다", english: "Analyze", pronunciation: "[ˈænəˌlaɪz]" },
    { korean: "시도하다", english: "Attempt", pronunciation: "[əˈtɛmpt]" },
    { korean: "수정하다", english: "Amend", pronunciation: "[əˈmɛnd]" },
    { korean: "확인하다", english: "Confirm", pronunciation: "[kənˈfɜrm]" },
    { korean: "기록하다", english: "Record", pronunciation: "[rɪˈkɔrd]" },
    { korean: "작성하다", english: "Draft", pronunciation: "[dræft]" },
    { korean: "통합하다", english: "Integrate", pronunciation: "[ˈɪntəˌɡreɪt]" },
    { korean: "분석하다", english: "Evaluate", pronunciation: "[ɪˈvæljueɪt]" },
    { korean: "확장하다", english: "Expand", pronunciation: "[ɪkˈspænd]" },
    { korean: "연구하다", english: "Investigate", pronunciation: "[ɪnˈvɛstəˌɡeɪt]" },
    { korean: "발견하다", english: "Detect", pronunciation: "[dɪˈtɛkt]" },
    { korean: "개발하다", english: "Develop", pronunciation: "[dɪˈvɛləp]" },
    { korean: "관리하다", english: "Administer", pronunciation: "[ədˈmɪnɪstər]" },
    { korean: "설명하다", english: "Explain", pronunciation: "[ɪkˈspleɪn]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "지속하다", english: "Sustain", pronunciation: "[səˈsteɪn]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "요청하다", english: "Request", pronunciation: "[rɪˈkwɛst]" },
    { korean: "확장하다", english: "Expand", pronunciation: "[ɪkˈspænd]" },
    { korean: "연구하다", english: "Investigate", pronunciation: "[ɪnˈvɛstəˌɡeɪt]" },
    { korean: "제공하다", english: "Provide", pronunciation: "[prəˈvaɪd]" },
    { korean: "보호하다", english: "Protect", pronunciation: "[prəˈtɛkt]" },
    { korean: "기록하다", english: "Record", pronunciation: "[rɪˈkɔrd]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "강조하다", english: "Emphasize", pronunciation: "[ˈɛmfəˌsaɪz]" },
    { korean: "관리하다", english: "Manage", pronunciation: "[ˈmænɪdʒ]" },
    { korean: "설명하다", english: "Explain", pronunciation: "[ɪkˈspleɪn]" },
    { korean: "확장하다", english: "Expand", pronunciation: "[ɪkˈspænd]" },
    { korean: "협력하다", english: "Collaborate", pronunciation: "[kəˈlæbəˌreɪt]" },
    { korean: "확보하다", english: "Secure", pronunciation: "[sɪˈkjʊr]" },
    { korean: "기대하다", english: "Anticipate", pronunciation: "[ænˈtɪsɪˌpeɪt]" },
    { korean: "제출하다", english: "Submit", pronunciation: "[səbˈmɪt]" },
    { korean: "감독하다", english: "Oversee", pronunciation: "[ˌoʊvərˈsi]" },
    { korean: "진행하다", english: "Proceed", pronunciation: "[prəˈsid]" },
    { korean: "시행하다", english: "Implement", pronunciation: "[ˈɪmpləˌmɛnt]" },
    { korean: "관리하다", english: "Supervise", pronunciation: "[ˈsuprəˌvaɪz]" },
    { korean: "조정하다", english: "Adjust", pronunciation: "[əˈdʒʌst]" },
    { korean: "기록하다", english: "Document", pronunciation: "[ˈdɒkjʊmənt]" },
    { korean: "포착하다", english: "Capture", pronunciation: "[ˈkæptʃər]" },
    { korean: "분석하다", english: "Analyze", pronunciation: "[ˈænəˌlaɪz]" },
    { korean: "강화하다", english: "Enhance", pronunciation: "[ɪnˈhæns]" },
    { korean: "확보하다", english: "Secure", pronunciation: "[sɪˈkjʊr]" },
    { korean: "시작하다", english: "Initiate", pronunciation: "[ɪˈnɪʃieɪt]" },
    { korean: "제공하다", english: "Offer", pronunciation: "[ˈɔfər]" },
    { korean: "대비하다", english: "Prepare", pronunciation: "[prɪˈpɛr]" },
    { korean: "요약하다", english: "Summarize", pronunciation: "[ˈsʌməˌraɪz]" },
    { korean: "분류하다", english: "Classify", pronunciation: "[ˈklæsɪˌfaɪ]" },
    { korean: "요청하다", english: "Request", pronunciation: "[rɪˈkwɛst]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "분석하다", english: "Analyze", pronunciation: "[ˈænəˌlaɪz]" },
    { korean: "연구하다", english: "Investigate", pronunciation: "[ɪnˈvɛstəˌɡeɪt]" },
    { korean: "조사하다", english: "Examine", pronunciation: "[ɪɡˈzæmɪn]" },
    { korean: "관리하다", english: "Administer", pronunciation: "[ədˈmɪnɪstər]" },
    { korean: "제공하다", english: "Provide", pronunciation: "[prəˈvaɪd]" },
    { korean: "보호하다", english: "Protect", pronunciation: "[prəˈtɛkt]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "강조하다", english: "Emphasize", pronunciation: "[ˈɛmfəˌsaɪz]" },
    { korean: "협력하다", english: "Collaborate", pronunciation: "[kəˈlæbəˌreɪt]" },
    { korean: "요청하다", english: "Request", pronunciation: "[rɪˈkwɛst]" },
    { korean: "설명하다", english: "Explain", pronunciation: "[ɪkˈspleɪn]" },
    { korean: "관리하다", english: "Supervise", pronunciation: "[ˈsuprəˌvaɪz]" },
    { korean: "제출하다", english: "Submit", pronunciation: "[səbˈmɪt]" },
    { korean: "기대하다", english: "Anticipate", pronunciation: "[ænˈtɪsɪˌpeɪt]" },
    { korean: "확인하다", english: "Verify", pronunciation: "[ˈvɛrəˌfaɪ]" },
    { korean: "확장하다", english: "Expand", pronunciation: "[ɪkˈspænd]" },
    { korean: "분석하다", english: "Analyze", pronunciation: "[ˈænəˌlaɪz]" },
    { korean: "예방하다", english: "Prevent", pronunciation: "[prɪˈvɛnt]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "관리하다", english: "Manage", pronunciation: "[ˈmænɪdʒ]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "진행하다", english: "Proceed", pronunciation: "[prəˈsid]" },
    { korean: "협력하다", english: "Collaborate", pronunciation: "[kəˈlæbəˌreɪt]" },
    { korean: "보호하다", english: "Protect", pronunciation: "[prəˈtɛkt]" },
    { korean: "작성하다", english: "Draft", pronunciation: "[dræft]" },
    { korean: "강조하다", english: "Emphasize", pronunciation: "[ˈɛmfəˌsaɪz]" },
    { korean: "제출하다", english: "Submit", pronunciation: "[səbˈmɪt]" },
    { korean: "기록하다", english: "Record", pronunciation: "[rɪˈkɔrd]" },
    { korean: "관리하다", english: "Supervise", pronunciation: "[ˈsuprəˌvaɪz]" },
    { korean: "시행하다", english: "Implement", pronunciation: "[ˈɪmpləˌmɛnt]" },
    { korean: "설명하다", english: "Explain", pronunciation: "[ɪkˈspleɪn]" },
    { korean: "확장하다", english: "Expand", pronunciation: "[ɪkˈspænd]" },
    { korean: "관리하다", english: "Administer", pronunciation: "[ədˈmɪnɪstər]" },
    { korean: "강화하다", english: "Enhance", pronunciation: "[ɪnˈhæns]" },
    { korean: "분석하다", english: "Analyze", pronunciation: "[ˈænəˌlaɪz]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "관리하다", english: "Manage", pronunciation: "[ˈmænɪdʒ]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "기대하다", english: "Anticipate", pronunciation: "[ænˈtɪsɪˌpeɪt]" },
    { korean: "제출하다", english: "Submit", pronunciation: "[səbˈmɪt]" },
    { korean: "강화하다", english: "Enhance", pronunciation: "[ɪnˈhæns]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "관리하다", english: "Administer", pronunciation: "[ədˈmɪnɪstər]" },
    { korean: "설명하다", english: "Explain", pronunciation: "[ɪkˈspleɪn]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "확장하다", english: "Expand", pronunciation: "[ɪkˈspænd]" },
    { korean: "관리하다", english: "Supervise", pronunciation: "[ˈsuprəˌvaɪz]" },
    { korean: "기록하다", english: "Record", pronunciation: "[rɪˈkɔrd]" },
    { korean: "제출하다", english: "Submit", pronunciation: "[səbˈmɪt]" },
    { korean: "관리하다", english: "Manage", pronunciation: "[ˈmænɪdʒ]" },
    { korean: "시행하다", english: "Implement", pronunciation: "[ˈɪmpləˌmɛnt]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "강화하다", english: "Enhance", pronunciation: "[ɪnˈhæns]" },
    { korean: "협력하다", english: "Collaborate", pronunciation: "[kəˈlæbəˌreɪt]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "기대하다", english: "Anticipate", pronunciation: "[ænˈtɪsɪˌpeɪt]" },
    { korean: "관리하다", english: "Supervise", pronunciation: "[ˈsuprəˌvaɪz]" },
    { korean: "제출하다", english: "Submit", pronunciation: "[səbˈmɪt]" },
    { korean: "강화하다", english: "Enhance", pronunciation: "[ɪnˈhæns]" },
    { korean: "관리하다", english: "Administer", pronunciation: "[ədˈmɪnɪstər]" },
    { korean: "설명하다", english: "Explain", pronunciation: "[ɪkˈspleɪn]" },
    { korean: "기대하다", english: "Anticipate", pronunciation: "[ænˈtɪsɪˌpeɪt]" },
    { korean: "확장하다", english: "Expand", pronunciation: "[ɪkˈspænd]" },
    { korean: "강화하다", english: "Enhance", pronunciation: "[ɪnˈhæns]" },
    { korean: "기록하다", english: "Record", pronunciation: "[rɪˈkɔrd]" },
    { korean: "기대하다", english: "Anticipate", pronunciation: "[ænˈtɪsɪˌpeɪt]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "설명하다", english: "Explain", pronunciation: "[ɪkˈspleɪn]" },
    { korean: "관리하다", english: "Administer", pronunciation: "[ədˈmɪnɪstər]" },
    { korean: "기록하다", english: "Record", pronunciation: "[rɪˈkɔrd]" },
    { korean: "강화하다", english: "Enhance", pronunciation: "[ɪnˈhæns]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "관리하다", english: "Supervise", pronunciation: "[ˈsuprəˌvaɪz]" },
    { korean: "제출하다", english: "Submit", pronunciation: "[səbˈmɪt]" },
    { korean: "관리하다", english: "Manage", pronunciation: "[ˈmænɪdʒ]" },
    { korean: "설명하다", english: "Explain", pronunciation: "[ɪkˈspleɪn]" },
    { korean: "기록하다", english: "Record", pronunciation: "[rɪˈkɔrd]" },
    { korean: "강화하다", english: "Enhance", pronunciation: "[ɪnˈhæns]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "관리하다", english: "Administer", pronunciation: "[ədˈmɪnɪstər]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "기대하다", english: "Anticipate", pronunciation: "[ænˈtɪsɪˌpeɪt]" },
    { korean: "제출하다", english: "Submit", pronunciation: "[səbˈmɪt]" },
    { korean: "상담하다", english: "Consult", pronunciation: "[kənˈsʌlt]" },
    { korean: "포함하다", english: "Encompass", pronunciation: "[ɪnˈkʌmpəs]" },
    { korean: "확장하다", english: "Expand", pronunciation: "[ɪkˈspænd]" },
    { korean: "복사하다", english: "Copy", pronunciation: "[ˈkɒpi]" },
    { korean: "예상하다", english: "Predict", pronunciation: "[prɪˈdɪkt]" },
    { korean: "지속하다", english: "Continue", pronunciation: "[kənˈtɪnjuː]" },
    { korean: "제출하다", english: "Submit", pronunciation: "[səbˈmɪt]" },
    { korean: "고려하다", english: "Consider", pronunciation: "[kənˈsɪdər]" },
    { korean: "완료하다", english: "Complete", pronunciation: "[kəmˈpliːt]" },
    { korean: "확신하다", english: "Assure", pronunciation: "[əˈʃʊr]" },
    { korean: "기부하다", english: "Donate", pronunciation: "[ˈdoʊneɪt]" },
    { korean: "동의하다", english: "Consent", pronunciation: "[kənˈsɛnt]" },
    { korean: "수락하다", english: "Accept", pronunciation: "[əkˈsɛpt]" },
    { korean: "조사하다", english: "Survey", pronunciation: "[ˈsɜːrveɪ]" },
    { korean: "도입하다", english: "Introduce", pronunciation: "[ˌɪntrəˈdus]" },
    { korean: "발표하다", english: "Declare", pronunciation: "[dɪˈklɛər]" },
    { korean: "유지하다", english: "Maintain", pronunciation: "[meɪnˈteɪn]" },
    { korean: "정리하다", english: "Organize", pronunciation: "[ˈɔːrɡənaɪz]" },
    { korean: "연결하다", english: "Connect", pronunciation: "[kəˈnɛkt]" },
    { korean: "방문하다", english: "Visit", pronunciation: "[ˈvɪzɪt]" },
    { korean: "기록하다", english: "Record", pronunciation: "[ˈrɛkɔrd]" },
    { korean: "복원하다", english: "Restore", pronunciation: "[rɪˈstɔːr]" },
    { korean: "계산하다", english: "Calculate", pronunciation: "[ˈkælkjəleɪt]" },
    { korean: "설득하다", english: "Convince", pronunciation: "[kənˈvɪns]" },
    { korean: "조정하다", english: "Modify", pronunciation: "[ˈmɒdəˌfaɪ]" },
    { korean: "분석하다", english: "Analyze", pronunciation: "[ˈænəˌlaɪz]" },
    { korean: "준비하다", english: "Prepare", pronunciation: "[prɪˈpɛər]" },
    { korean: "예방하다", english: "Prevent", pronunciation: "[prɪˈvɛnt]" },
    { korean: "응답하다", english: "Respond", pronunciation: "[rɪˈspɒnd]" },
    { korean: "보호하다", english: "Defend", pronunciation: "[dɪˈfɛnd]" },
    { korean: "포기하다", english: "Abandon", pronunciation: "[əˈbændən]" },
    { korean: "보증하다", english: "Guarantee", pronunciation: "[ˌɡærənˈtiː]" },
    { korean: "통합하다", english: "Unify", pronunciation: "[ˈjuːnɪfaɪ]" }
   // 추가할 중고등학생 필수 동사들을 계속 추가하세요.
];

let currentWordIndex = 0;
let pronounceInterval;
let synth = window.speechSynthesis;
let autoPlayInterval;

function updateWord() {
    document.getElementById('word-korean').innerText = words[currentWordIndex].korean;
    document.getElementById('word-english').innerText = words[currentWordIndex].english;
    document.getElementById('word-pronunciation').innerText = words[currentWordIndex].pronunciation;
}

function pronounceWord(times, callback) {
    let count = 0;

    function speak() {
        if (count < times) {
            let koreanUtterance = new SpeechSynthesisUtterance(words[currentWordIndex].korean);
            koreanUtterance.lang = 'ko-KR'; // 한국어 발음 설정
            koreanUtterance.rate = 1; // 발음 속도 설정 (1배 빠르게)

            let englishUtterance = new SpeechSynthesisUtterance(words[currentWordIndex].english);
            englishUtterance.lang = 'en-US'; // 영어 발음 설정
            englishUtterance.rate = 1; // 발음 속도 설정 (1배 빠르게)

            koreanUtterance.onend = () => {
                synth.speak(englishUtterance);
            };

            englishUtterance.onend = () => {
                count++;
                if (count < times) {
                    speak();
                } else if (callback) {
                    callback();
                }
            };

            synth.speak(koreanUtterance);
        }
    }

    speak();
}

function stopPronouncing() {
    clearInterval(pronounceInterval);
    clearInterval(autoPlayInterval);
    synth.cancel();
}

function nextWord() {
    currentWordIndex = (currentWordIndex + 1) % words.length;
    updateWord();
    pronounceWord(1);
}

function autoPlay() {
    stopPronouncing();
    currentWordIndex = 0; // 처음부터 시작
    autoPlayInterval = setInterval(() => {
        updateWord();
        pronounceWord(1, () => {
            currentWordIndex++;
            if (currentWordIndex >= words.length) {
                currentWordIndex = 0; // 끝에 도달하면 처음으로 돌아가기
            }
        });
    }, 8000); // 6초마다 다음 단어로 넘어가고 발음 (발음 시간 3초 + 대기 시간 3초)
}

updateWord();

// 단어 목록을 화면에 표시하는 함수
function showWordList() {
    const wordList = document.getElementById('word-list');
    words.forEach(word => {
        const listItem = document.createElement('li');
        listItem.classList.add('list-group-item');
        listItem.innerHTML = `<strong>${word.korean}</strong><br>${word.english}<em><br>${word.pronunciation}</em><br><br>`;
        wordList.appendChild(listItem);
    });
}

document.addEventListener('DOMContentLoaded', () => {
    updateWord();
    showWordList(); // 페이지 로드 시 단어 목록 표시
});

