document.addEventListener('DOMContentLoaded', function() {
    const generateButton = document.getElementById('generateButton');
    const loadingSection = document.getElementById('loading');
    const resultsSection = document.getElementById('results');
    const sentenceList = document.getElementById('sentenceList');
    const topicInput = document.getElementById('topicInput');

    const keywords = {
        examples: [
            "decide travel purpose(여행 목적 결정하다)",
            "set budget(예산 설정하다)",
            "choose destination(여행지 선택하다)",
            "book flight(항공편 예약하다)",
            "book hotel(호텔 예약하다)",
            "buy travel insurance(여행 보험 가입하다)",
            "apply for visa(비자 발급 신청하다)",
            "check passport validity(여권 유효기간 확인하다)",
            "plan itinerary(여행 일정 계획하다)",
            "make packing list(필수 물품 리스트 작성하다)",
            "pack luggage(짐 싸다)",
            "prepare for airport transfer(공항 이동 준비하다)",
            "arrange pet care(애완동물 돌봄 준비하다)",
            "inform family and friends(가족과 친구들에게 알리다)",
            "exchange currency(환전하다)",
            "download travel apps(여행 앱 다운로드하다)",
            "check weather forecast(날씨 예보 확인하다)",
            "set out-of-office email(부재중 이메일 설정하다)",
            "confirm flight details(항공편 세부 사항 확인하다)",
            "print travel documents(여행 서류 출력하다)",
            "notify bank of travel(은행에 여행 알리다)",
            "prepare travel snacks(여행 간식 준비하다)",
            "charge electronic devices(전자 기기 충전하다)",
            "arrange airport parking(공항 주차 예약하다)",
            "schedule transportation to airport(공항까지 교통편 예약하다)",
            "check baggage allowance(수하물 허용량 확인하다)",
            "label luggage(짐에 라벨 붙이다)",
            "get travel vaccinations(여행 예방 접종 받다)",
            "photocopy important documents(중요 서류 복사하다)",
            "create emergency contact list(비상 연락처 목록 작성하다)",
            "set travel itinerary(여행 일정 설정하다)",
            "download offline maps(오프라인 지도 다운로드하다)",
            "purchase travel guidebook(여행 가이드북 구입하다)",
            "review local customs(현지 관습 검토하다)",
            "pack toiletries(세면도구 챙기다)",
            "prepare first aid kit(구급 상자 준비하다)",
            "purchase travel accessories(여행 용품 구입하다)",
            "check electrical outlet types(전기 콘센트 종류 확인하다)",
            "pack travel-sized items(여행용 크기 물품 챙기다)",
            "confirm hotel reservation(호텔 예약 확인하다)",
            "reserve restaurant seats(레스토랑 좌석 예약하다)",
            "learn basic local phrases(현지 기본 표현 배우다)",
            "secure home before leaving(떠나기 전에 집을 안전하게 하다)",
            "arrange for mail hold(우편물 보류 신청하다)",
            "notify neighbors of travel plans(이웃에게 여행 계획 알리다)",
            "check flight status(항공편 상태 확인하다)",
            "prepare travel itinerary copies(여행 일정 복사본 준비하다)",
            "pack travel entertainment(여행 오락거리 챙기다)",
            "download travel music playlist(여행 음악 플레이리스트 다운로드하다)",
            "pack reusable water bottle(재사용 가능한 물병 챙기다)",
            "buy travel adapters(여행용 어댑터 구입하다)",
            "prepare for jet lag(시차 적응 준비하다)",
            "study travel safety tips(여행 안전 팁 공부하다)",
            "check travel restrictions(여행 제한 확인하다)",
            "update travel vaccinations(여행 예방 접종 업데이트하다)",
            "prepare travel budget spreadsheet(여행 예산 스프레드시트 준비하다)",
            "pack travel clothes(여행 옷 챙기다)",
            "prepare travel documents folder(여행 서류 폴더 준비하다)",
            "check international roaming plans(국제 로밍 요금제 확인하다)",
            "download travel language apps(여행 언어 앱 다운로드하다)",
            "check local emergency numbers(현지 비상 전화번호 확인하다)",
            "prepare for travel delays(여행 지연 대비하다)",
            "create travel bucket list(여행 버킷리스트 작성하다)",
            "book travel activities(여행 활동 예약하다)",
            "pack travel snacks(여행 간식 챙기다)",
            "arrange for house sitter(집 돌봄이 준비하다)",
            "schedule travel vaccinations(여행 예방 접종 일정 잡다)",
            "learn about local cuisine(현지 요리 공부하다)",
            "purchase travel insurance policy(여행 보험 증권 구입하다)",
            "check flight updates(항공편 업데이트 확인하다)",
            "prepare travel budget(여행 예산 준비하다)",
            "pack travel shoes(여행 신발 챙기다)",
            "prepare travel first aid kit(여행용 구급 상자 준비하다)",
            "check local weather(현지 날씨 확인하다)",
            "pack travel medicine(여행 약 챙기다)",
            "confirm transportation details(교통편 세부 사항 확인하다)",
            "prepare travel documents(여행 서류 준비하다)",
            "download travel guides(여행 가이드 다운로드하다)",
            "prepare travel toiletries(여행 세면도구 준비하다)",
            "check local customs and etiquette(현지 관습 및 예절 확인하다)",
            "review travel itinerary(여행 일정 검토하다)",
            "prepare for travel jet lag(여행 시차 적응 준비하다)",
            "secure home for travel(여행 중 집을 안전하게 하다)",
            "notify family of travel plans(가족에게 여행 계획 알리다)",
            "prepare travel money(여행 자금 준비하다)",
            "check for travel alerts(여행 경고 확인하다)",
            "pack travel electronics(여행 전자 기기 챙기다)",
            "schedule travel vaccinations(여행 예방 접종 예약하다)",
            "arrange for travel documents(여행 서류 준비하다)",
            "confirm travel reservations(여행 예약 확인하다)",
            "prepare travel snacks(여행 간식 준비하다)",
            "download travel apps(여행 앱 다운로드하다)",
            "check travel restrictions(여행 제한 확인하다)",
            "prepare travel budget(여행 예산 준비하다)",
            "pack travel clothes(여행 옷 챙기다)",
            "prepare travel documents(여행 서류 준비하다)",
            "check local weather(현지 날씨 확인하다)",
            "review travel itinerary(여행 일정 검토하다)",
            "prepare travel money(여행 자금 준비하다)",
            "check for travel alerts(여행 경고 확인하다)",
            "notify family of travel plans(가족에게 여행 계획 알리다)",
            "secure home for travel(여행 중 집을 안전하게 하다)",
            "download travel guides(여행 가이드 다운로드하다)",
            "confirm travel reservations(여행 예약 확인하다)",
            "pack travel toiletries(여행 세면도구 챙기다)",
            "prepare travel medicine(여행 약 챙기다)",
            "check travel restrictions(여행 제한 확인하다)",
            "prepare for travel jet lag(여행 시차 적응 준비하다)",
            "schedule travel vaccinations(여행 예방 접종 예약하다)",
            "arrange for house sitter(집 돌봄이 준비하다)",
            "prepare travel budget(여행 예산 준비하다)",
            "pack travel electronics(여행 전자 기기 챙기다)",
            "check local customs and etiquette(현지 관습 및 예절 확인하다)",
            "prepare travel documents folder(여행 서류 폴더 준비하다)",
            "download travel language apps(여행 언어 앱 다운로드하다)",
            "check international roaming plans(국제 로밍 요금제 확인하다)",
            "create travel bucket list(여행 버킷리스트 작성하다)",
            "prepare for travel delays(여행 지연 대비하다)",
            "check local emergency numbers(현지 비상 전화번호 확인하다)",
            "book travel activities(여행 활동 예약하다)",
            "learn about local cuisine(현지 요리 공부하다)",
            "purchase travel insurance policy(여행 보험 증권 구입하다)",
            "prepare travel budget spreadsheet(여행 예산 스프레드시트 준비하다)",
            "update travel vaccinations(여행 예방 접종 업데이트하다)",
            "study travel safety tips(여행 안전 팁 공부하다)",
            "pack travel snacks(여행 간식 챙기다)",
            "buy travel adapters(여행용 어댑터 구입하다)",
            "pack reusable water bottle(재사용 가능한 물병 챙기다)",
            "download travel music playlist(여행 음악 플레이리스트 다운로드하다)",
            "pack travel entertainment(여행 오락거리 챙기다)",
            "prepare travel itinerary copies(여행 일정 복사본 준비하다)",
            "check flight status(항공편 상태 확인하다)",
            "notify neighbors of travel plans(이웃에게 여행 계획 알리다)",
            "arrange for mail hold(우편물 보류 신청하다)",
            "secure home before leaving(떠나기 전에 집을 안전하게 하다)",
            "learn basic local phrases(현지 기본 표현 배우다)",
            "reserve restaurant seats(레스토랑 좌석 예약하다)",
            "confirm hotel reservation(호텔 예약 확인하다)",
            "pack travel-sized items(여행용 크기 물품 챙기다)",
            "check electrical outlet types(전기 콘센트 종류 확인하다)",
            "purchase travel accessories(여행 용품 구입하다)",
            "prepare first aid kit(구급 상자 준비하다)",
            "pack toiletries(세면도구 챙기다)",
            "review local customs(현지 관습 검토하다)",
            "purchase travel guidebook(여행 가이드북 구입하다)",
            "download offline maps(오프라인 지도 다운로드하다)",
            "set travel itinerary(여행 일정 설정하다)",
            "create emergency contact list(비상 연락처 목록 작성하다)",
            "photocopy important documents(중요 서류 복사하다)",
            "get travel vaccinations(여행 예방 접종 받다)",
            "label luggage(짐에 라벨 붙이다)",
            "check baggage allowance(수하물 허용량 확인하다)",
            "schedule transportation to airport(공항까지 교통편 예약하다)",
            "arrange airport parking(공항 주차 예약하다)",
            "charge electronic devices(전자 기기 충전하다)",
            "prepare travel snacks(여행 간식 준비하다)",
            "notify bank of travel(은행에 여행 알리다)",
            "print travel documents(여행 서류 출력하다)",
            "confirm flight details(항공편 세부 사항 확인하다)",
            "set out-of-office email(부재중 이메일 설정하다)",
            "check weather forecast(날씨 예보 확인하다)",
            "download travel apps(여행 앱 다운로드하다)",
            "exchange currency(환전하다)",
            "inform family and friends(가족과 친구들에게 알리다)",
            "arrange pet care(애완동물 돌봄 준비하다)",
            "prepare for airport transfer(공항 이동 준비하다)",
            "pack luggage(짐 싸다)",
            "make packing list(필수 물품 리스트 작성하다)",
            "plan itinerary(여행 일정 계획하다)",
            "check passport validity(여권 유효기간 확인하다)",
            "apply for visa(비자 발급 신청하다)",
            "buy travel insurance(여행 보험 가입하다)",
            "book hotel(호텔 예약하다)",
            "book flight(항공편 예약하다)",
            "choose destination(여행지 선택하다)",
            "set budget(예산 설정하다)",
            "decide travel purpose(여행 목적 결정하다)",
            "review local laws(현지 법률 검토하다)",
            "prepare for language barriers(언어 장벽 대비하다)",
            "check for travel advisories(여행 주의보 확인하다)",
            "arrange for airport lounge access(공항 라운지 접근 예약하다)",
            "update travel budget(여행 예산 업데이트하다)",
            "check for public transportation options(대중 교통 옵션 확인하다)",
            "review hotel amenities(호텔 편의 시설 검토하다)",
            "prepare for cultural differences(문화 차이 대비하다)",
            "confirm car rental(렌터카 예약 확인하다)",
            "purchase travel gear(여행 장비 구입하다)",
            "arrange for pet sitter(애완동물 돌봄이 준비하다)",
            "create packing list(짐 싸기 목록 작성하다)",
            "prepare travel checklist(여행 체크리스트 준비하다)",
            "arrange for travel vaccinations(여행 예방 접종 준비하다)",
            "book travel excursions(여행 투어 예약하다)",
            "download travel entertainment(여행 오락거리 다운로드하다)",
            "check for travel promotions(여행 프로모션 확인하다)",
            "prepare for travel delays(여행 지연 대비하다)",
            "arrange for travel currency(여행 통화 준비하다)",
            "check for travel discounts(여행 할인 확인하다)",
            "review travel policies(여행 정책 검토하다)",
            "pack travel documents(여행 서류 챙기다)",
            "prepare for travel emergencies(여행 비상 사태 대비하다)",
            "check for travel updates(여행 업데이트 확인하다)",
            "secure travel insurance(여행 보험 확보하다)",
            "prepare travel electronics(여행 전자 기기 준비하다)",
            "check travel itinerary(여행 일정 확인하다)",
            "notify travel companions(여행 동반자에게 알리다)",
            "check for travel warnings(여행 경고 확인하다)",
            "prepare travel wardrobe(여행 옷 준비하다)",
            "arrange for travel guides(여행 가이드 준비하다)",
            "download travel maps(여행 지도 다운로드하다)",
            "confirm travel plans(여행 계획 확인하다)",
            "prepare for travel security(여행 보안 준비하다)",
            "review travel destinations(여행 목적지 검토하다)",
            "pack travel snacks(여행 간식 챙기다)",
            "prepare for travel expenses(여행 비용 준비하다)",
            "check travel routes(여행 경로 확인하다)",
            "secure travel documents(여행 서류 확보하다)",
            "prepare travel budget(여행 예산 준비하다)",
            "review travel guidelines(여행 지침 검토하다)",
            "pack travel essentials(여행 필수품 챙기다)",
            "arrange for travel activities(여행 활동 준비하다)",
            "confirm travel reservations(여행 예약 확인하다)",
            "check for travel restrictions(여행 제한 확인하다)",
            "prepare travel itinerary(여행 일정 준비하다)",
            "download travel apps(여행 앱 다운로드하다)",
            "exchange travel currency(여행 통화 환전하다)",
            "prepare travel documents(여행 서류 준비하다)",
            "review travel plans(여행 계획 검토하다)",
            "pack travel toiletries(여행 세면도구 챙기다)",
            "check travel insurance(여행 보험 확인하다)",
            "prepare travel medicine(여행 약 준비하다)",
            "arrange for travel vaccinations(여행 예방 접종 준비하다)",
            "confirm travel flights(여행 항공편 확인하다)",
            "book travel accommodation(여행 숙박 예약하다)",
            "prepare travel checklist(여행 체크리스트 준비하다)",
            "notify family of travel plans(가족에게 여행 계획 알리다)",
            "check for travel alerts(여행 경고 확인하다)",
            "secure home before travel(여행 전 집을 안전하게 하다)",
            "prepare for travel jet lag(여행 시차 적응 준비하다)",
            "pack travel electronics(여행 전자 기기 챙기다)",
            "arrange for travel insurance(여행 보험 준비하다)",
            "prepare travel budget(여행 예산 준비하다)",
            "check local weather(현지 날씨 확인하다)",
            "confirm travel reservations(여행 예약 확인하다)",
            "prepare travel documents(여행 서류 준비하다)",
            "arrange for travel vaccinations(여행 예방 접종 준비하다)",
            "check travel restrictions(여행 제한 확인하다)",
            "review travel plans(여행 계획 검토하다)",
            "pack travel toiletries(여행 세면도구 챙기다)",
            "prepare for travel delays(여행 지연 대비하다)",
            "secure travel insurance(여행 보험 확보하다)",
            "prepare travel medicine(여행 약 준비하다)",
            "check for travel updates(여행 업데이트 확인하다)",
            "pack travel snacks(여행 간식 챙기다)",
            "prepare travel wardrobe(여행 옷 준비하다)",
            "confirm travel plans(여행 계획 확인하다)",
            "review travel itinerary(여행 일정 검토하다)",
            "prepare for travel security(여행 보안 준비하다)",
            "download travel apps(여행 앱 다운로드하다)",
            "prepare travel budget(여행 예산 준비하다)",
            "check for travel warnings(여행 경고 확인하다)",
            "arrange for travel guides(여행 가이드 준비하다)",
            "download travel maps(여행 지도 다운로드하다)",
            "notify travel companions(여행 동반자에게 알리다)",
            "secure travel documents(여행 서류 확보하다)",
            "pack travel essentials(여행 필수품 챙기다)",
            "review travel guidelines(여행 지침 검토하다)",
            "prepare travel documents folder(여행 서류 폴더 준비하다)",
            "check local customs and etiquette(현지 관습 및 예절 확인하다)",
            "confirm travel reservations(여행 예약 확인하다)",
            "prepare for travel emergencies(여행 비상 사태 대비하다)",
            "check for travel discounts(여행 할인 확인하다)",
            "arrange for house sitter(집 돌봄이 준비하다)",
            "book travel excursions(여행 투어 예약하다)",
            "prepare travel checklist(여행 체크리스트 준비하다)",
            "check local emergency numbers(현지 비상 전화번호 확인하다)",
            "prepare for language barriers(언어 장벽 대비하다)",
            "review travel policies(여행 정책 검토하다)",
            "secure home for travel(여행 중 집을 안전하게 하다)",
            "prepare for cultural differences(문화 차이 대비하다)",
            "pack travel documents(여행 서류 챙기다)",
            "check travel itinerary(여행 일정 확인하다)",
            "notify neighbors of travel plans(이웃에게 여행 계획 알리다)",
            "prepare for travel delays(여행 지연 대비하다)",
            "confirm transportation details(교통편 세부 사항 확인하다)",
            "pack travel medicine(여행 약 챙기다)",
            "prepare travel toiletries(여행 세면도구 준비하다)",
            "review hotel amenities(호텔 편의 시설 검토하다)",
            "pack travel snacks(여행 간식 챙기다)",
            "check flight status(항공편 상태 확인하다)",
            "exchange currency(환전하다)",
            "check passport validity(여권 유효기간 확인하다)",
            "apply for visa(비자 발급 신청하다)",
            "check weather forecast(날씨 예보 확인하다)",
            "download travel guides(여행 가이드 다운로드하다)",
            "print travel documents(여행 서류 출력하다)",
            "notify bank of travel(은행에 여행 알리다)",
            "set out-of-office email(부재중 이메일 설정하다)",
            "confirm flight details(항공편 세부 사항 확인하다)",
            "arrange pet care(애완동물 돌봄 준비하다)",
            "prepare for airport transfer(공항 이동 준비하다)",
            "arrange airport parking(공항 주차 예약하다)",
            "schedule transportation to airport(공항까지 교통편 예약하다)",
            "check baggage allowance(수하물 허용량 확인하다)",
            "label luggage(짐에 라벨 붙이다)",
            "get travel vaccinations(여행 예방 접종 받다)",
            "create emergency contact list(비상 연락처 목록 작성하다)",
            "photocopy important documents(중요 서류 복사하다)",
            "set travel itinerary(여행 일정 설정하다)",
            "download offline maps(오프라인 지도 다운로드하다)",
            "purchase travel guidebook(여행 가이드북 구입하다)",
            "review local customs(현지 관습 검토하다)",
            "pack toiletries(세면도구 챙기다)",
            "prepare first aid kit(구급 상자 준비하다)",
            "purchase travel accessories(여행 용품 구입하다)",
            "check electrical outlet types(전기 콘센트 종류 확인하다)",
            "pack travel-sized items(여행용 크기 물품 챙기다)",
            "confirm hotel reservation(호텔 예약 확인하다)",
            "reserve restaurant seats(레스토랑 좌석 예약하다)",
            "learn basic local phrases(현지 기본 표현 배우다)",
            "secure home before leaving(떠나기 전에 집을 안전하게 하다)",
            "arrange for mail hold(우편물 보류 신청하다)",
            "notify neighbors of travel plans(이웃에게 여행 계획 알리다)",
            "check flight status(항공편 상태 확인하다)",
            "prepare travel itinerary copies(여행 일정 복사본 준비하다)",
            "pack travel entertainment(여행 오락거리 챙기다)",
            "download travel music playlist(여행 음악 플레이리스트 다운로드하다)",
            "pack reusable water bottle(재사용 가능한 물병 챙기다)",
            "buy travel adapters(여행용 어댑터 구입하다)",
            "prepare for jet lag(시차 적응 준비하다)",
            "study travel safety tips(여행 안전 팁 공부하다)",
            "check travel restrictions(여행 제한 확인하다)",
            "update travel vaccinations(여행 예방 접종 업데이트하다)",
            "prepare travel budget spreadsheet(여행 예산 스프레드시트 준비하다)",
            "pack travel clothes(여행 옷 챙기다)",
            "prepare travel documents folder(여행 서류 폴더 준비하다)",
            "check international roaming plans(국제 로밍 요금제 확인하다)",
            "download travel language apps(여행 언어 앱 다운로드하다)",
            "check local emergency numbers(현지 비상 전화번호 확인하다)",
            "prepare for travel delays(여행 지연 대비하다)",
            "create travel bucket list(여행 버킷리스트 작성하다)",
            "book travel activities(여행 활동 예약하다)",
            "pack travel snacks(여행 간식 챙기다)",
            "arrange for house sitter(집 돌봄이 준비하다)",
            "schedule travel vaccinations(여행 예방 접종 일정 잡다)",
            "learn about local cuisine(현지 요리 공부하다)",
            "purchase travel insurance policy(여행 보험 증권 구입하다)",
            "check flight updates(항공편 업데이트 확인하다)",
            "prepare travel budget(여행 예산 준비하다)",
            "pack travel shoes(여행 신발 챙기다)",
            "prepare travel first aid kit(여행용 구급 상자 준비하다)",
            "check local weather(현지 날씨 확인하다)",
            "pack travel medicine(여행 약 챙기다)",
            "confirm transportation details(교통편 세부 사항 확인하다)",
            "prepare travel documents(여행 서류 준비하다)",
            "download travel guides(여행 가이드 다운로드하다)",
            "prepare travel toiletries(여행 세면도구 준비하다)",
            "check local customs and etiquette(현지 관습 및 예절 확인하다)",
            "review travel itinerary(여행 일정 검토하다)",
            "prepare for travel jet lag(여행 시차 적응 준비하다)",
            "secure home for travel(여행 중 집을 안전하게 하다)",
            "notify family of travel plans(가족에게 여행 계획 알리다)",
            "prepare travel money(여행 자금 준비하다)",
            "check for travel alerts(여행 경고 확인하다)",
            "pack travel electronics(여행 전자 기기 챙기다)",
            "schedule travel vaccinations(여행 예방 접종 예약하다)",
            "arrange for travel documents(여행 서류 준비하다)",
            "confirm travel reservations(여행 예약 확인하다)",
            "prepare travel snacks(여행 간식 준비하다)",
            "download travel apps(여행 앱 다운로드하다)",
            "check travel restrictions(여행 제한 확인하다)",
            "prepare travel budget(여행 예산 준비하다)",
            "pack travel clothes(여행 옷 챙기다)",
            "prepare travel documents(여행 서류 준비하다)",
            "check local weather(현지 날씨 확인하다)",
            "review travel itinerary(여행 일정 검토하다)",
            "prepare travel money(여행 자금 준비하다)",
            "check for travel alerts(여행 경고 확인하다)",
            "notify family of travel plans(가족에게 여행 계획 알리다)",
            "secure home for travel(여행 중 집을 안전하게 하다)",
            "download travel guides(여행 가이드 다운로드하다)",
            "confirm travel reservations(여행 예약 확인하다)",
            "pack travel toiletries(여행 세면도구 챙기다)",
            "prepare travel medicine(여행 약 챙기다)",
            "check travel restrictions(여행 제한 확인하다)",
            "prepare for travel jet lag(여행 시차 적응 준비하다)",
            "schedule travel vaccinations(여행 예방 접종 예약하다)",
            "arrange for house sitter(집 돌봄이 준비하다)",
            "prepare travel budget(여행 예산 준비하다)",
            "pack travel electronics(여행 전자 기기 챙기다)",
            "check local customs and etiquette(현지 관습 및 예절 확인하다)",
            "prepare travel documents folder(여행 서류 폴더 준비하다)",
            "download travel language apps(여행 언어 앱 다운로드하다)",
            "check international roaming plans(국제 로밍 요금제 확인하다)",
            "create travel bucket list(여행 버킷리스트 작성하다)",
            "prepare for travel delays(여행 지연 대비하다)",
            "check local emergency numbers(현지 비상 전화번호 확인하다)",
            "book travel activities(여행 활동 예약하다)",
            "learn about local cuisine(현지 요리 공부하다)",
            "purchase travel insurance policy(여행 보험 증권 구입하다)",
            "prepare travel budget spreadsheet(여행 예산 스프레드시트 준비하다)",
            "update travel vaccinations(여행 예방 접종 업데이트하다)",
            "study travel safety tips(여행 안전 팁 공부하다)",
            "pack travel snacks(여행 간식 챙기다)",
            "buy travel adapters(여행용 어댑터 구입하다)",
            "pack reusable water bottle(재사용 가능한 물병 챙기다)",
            "download travel music playlist(여행 음악 플레이리스트 다운로드하다)",
            "pack travel entertainment(여행 오락거리 챙기다)",
            "prepare travel itinerary copies(여행 일정 복사본 준비하다)",
            "check flight status(항공편 상태 확인하다)",
            "notify neighbors of travel plans(이웃에게 여행 계획 알리다)",
            "arrange for mail hold(우편물 보류 신청하다)",
            "secure home before leaving(떠나기 전에 집을 안전하게 하다)",
            "learn basic local phrases(현지 기본 표현 배우다)",
            "reserve restaurant seats(레스토랑 좌석 예약하다)",
            "confirm hotel reservation(호텔 예약 확인하다)",
            "pack travel-sized items(여행용 크기 물품 챙기다)",
            "check electrical outlet types(전기 콘센트 종류 확인하다)",
            "purchase travel accessories(여행 용품 구입하다)",
            "prepare first aid kit(구급 상자 준비하다)",
            "pack toiletries(세면도구 챙기다)",
            "review local customs(현지 관습 검토하다)",
            "purchase travel guidebook(여행 가이드북 구입하다)",
            "download offline maps(오프라인 지도 다운로드하다)",
            "set travel itinerary(여행 일정 설정하다)",
            "create emergency contact list(비상 연락처 목록 작성하다)",
            "photocopy important documents(중요 서류 복사하다)",
            "get travel vaccinations(여행 예방 접종 받다)",
            "label luggage(짐에 라벨 붙이다)",
            "check baggage allowance(수하물 허용량 확인하다)",
            "schedule transportation to airport(공항까지 교통편 예약하다)",
            "arrange airport parking(공항 주차 예약하다)",
            "charge electronic devices(전자 기기 충전하다)",
            "prepare travel snacks(여행 간식 준비하다)",
            "notify bank of travel(은행에 여행 알리다)",
            "print travel documents(여행 서류 출력하다)",
            "confirm flight details(항공편 세부 사항 확인하다)",
            "set out-of-office email(부재중 이메일 설정하다)",
            "check weather forecast(날씨 예보 확인하다)",
            "download travel apps(여행 앱 다운로드하다)",
            "exchange currency(환전하다)",
            "inform family and friends(가족과 친구들에게 알리다)",
            "arrange pet care(애완동물 돌봄 준비하다)",
            "prepare for airport transfer(공항 이동 준비하다)",
            "pack luggage(짐 싸다)",
            "make packing list(필수 물품 리스트 작성하다)",
            "plan itinerary(여행 일정 계획하다)",
            "check passport validity(여권 유효기간 확인하다)",
            "apply for visa(비자 발급 신청하다)",
            "buy travel insurance(여행 보험 가입하다)",
            "book hotel(호텔 예약하다)",
            "book flight(항공편 예약하다)",
            "choose destination(여행지 선택하다)",
            "set budget(예산 설정하다)",
            "decide travel purpose(여행 목적 결정하다)",
        ]
    };
    

    const keywordList = document.getElementById('keywordList');
    for (const category in keywords) {
        // Create and append the category headline
        const headline = document.createElement('h3');
        headline.textContent = category.charAt(0).toUpperCase() + category.slice(1);
        headline.classList.add('keyword-headline'); // *** Add a class for styling ***
        keywordList.appendChild(headline);

        // Append each keyword under the respective headline
        keywords[category].forEach(keyword => {
            const li = document.createElement('li');
            li.textContent = keyword;
            li.addEventListener('click', async () => {
                topicInput.value = keyword;
                topicInput.scrollIntoView({ behavior: 'smooth' });

                resultsSection.style.display = 'none';
                loadingSection.style.display = 'block';

                try {
                    const sentences = await generateSentences(keyword);
                    displaySentences(sentences);
                } catch (error) {
                    alert('Error generating sentences. Please try again later.');
                } finally {
                    loadingSection.style.display = 'none';
                }
            });
            keywordList.appendChild(li);
        });
    }

    generateButton.addEventListener('click', async function() {
        const topic = topicInput.value.trim();

        if (!topic) {
            alert('Please enter a topic.');
            return;
        }

        document.getElementById('selectedTopic').innerText = topic;
        resultsSection.style.display = 'none';
        loadingSection.style.display = 'block';

        try {
            const sentences = await generateSentences(topic);
            displaySentences(sentences);
        } catch (error) {
            alert('Error generating sentences. Please try again later.');
        } finally {
            loadingSection.style.display = 'none';
        }
    });

    async function generateSentences(topic) {
        try {
            const response = await fetch('http://localhost:3000/generate-sentences-routines', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ topic: topic })
            });

            if (!response.ok) throw new Error(`HTTP error! status: ${response.status}`);

            const data = await response.json();
            return data.sentences;
        } catch (error) {
            console.error('Error generating sentences:', error);
            throw error;
        }
    }

    function displaySentences(sentences) {
        sentenceList.innerHTML = '';
        sentences.split('\n').forEach(sentence => {
            const li = document.createElement('li');
            li.textContent = sentence;

            const readButton = document.createElement('button');
            readButton.textContent = 'Read';
            readButton.style.marginLeft = '10px';
            readButton.addEventListener('click', () => readSentence(sentence));
            li.appendChild(readButton);

            sentenceList.appendChild(li);
        });
        resultsSection.style.display = 'block';
    }

    function readSentence(sentence) {
        const englishPart = sentence.match(/^[^\(]+/)[0].trim();
        const utterance = new SpeechSynthesisUtterance(englishPart);
        utterance.lang = 'en-US';
        utterance.rate = 1;
        window.speechSynthesis.speak(utterance);
    }
});